// Civil Engineering optional: syllabus sub-topics in syllabus order, with the words that tie a past question to each.
//   s  : the official item (I-1.1 ... II-5) the sub-topic is filed under (see items.js)
//   re : pattern tested against the question text (case-insensitive); written as a regex literal, stored as its source
//   ex : a question that also matches this is NOT filed under the topic
//   p  : 1 or 2 limits the topic to that paper (omit = both)
// A question can belong to several topics (UPSC often joins two ideas in one question).
// Re-run with:  node upsc-pyq-bank/tools/optional/civil-engineering/build-civil.js
const S = function(r){ return r.source; };
module.exports = [
 // ================= PAPER I =================
 // I-1.1 Engineering mechanics
 {s:"I-1.1", p:1, t:"Equilibrium of forces, free body diagrams, moments and support reactions", re:S(/free body|equilibrium|\blever\b|pulley|moment of force|concurrent|reaction (forces|at)|support reactions|\blink\b|hinged (at|to)|friction ?less/), ex:S(/pile|retaining wall|footing|soil/)},
 {s:"I-1.1", p:1, t:"Static friction: blocks on inclined planes and impending motion", re:S(/static and kinetic|coefficient of (static|kinetic) friction|friction force|impending|block.{0,40}inclined|inclined plane|coefficient of friction for all/), ex:S(/pile|locomotive|prestress|pavement|base friction/)},
 {s:"I-1.1", p:1, t:"Principle of virtual work", re:S(/virtual work/)},
 {s:"I-1.1", p:1, t:"Kinematics and kinetics of a particle: motion under acceleration, momentum, energy and collisions", re:S(/particle moves|moves from the origin|acceleration along|velocity of the particle|projectile|collision|equation to the path|minimum velocity of the particle/)},
 {s:"I-1.1", p:1, t:"Moments of area, centroid and mass moment of inertia", re:S(/first and second moment|centroid|centre of gravity|mass moment of inertia|second moment of area|radius of gyration/)},
 // I-1.2 Strength of materials
 {s:"I-1.2", p:1, t:"Simple stress and strain, axially loaded members and elastic constants", re:S(/axial deformation|fixed-end bar|axially loaded|axial force|poisson|elastic constants?|modulus of elasticity|bulk modulus|rod shown|bars? of .{0,30}dia.{0,40}connected|segments? .{0,30}cross-sectional area|compression member was to be loaded|stresses at points A, B, C and D/), ex:S(/pile|soil|prestress/)},
 {s:"I-1.2", p:1, t:"Principal stresses, theories of failure and stress transformation", re:S(/principal stress|maximum shear stress theory|maximum principal stress theory|stress components|mohr'?s circle of stress|von mises|strain energy theory/), ex:S(/soil|triaxial|deviator|cell pressure|cohesion|sand|clay/)},
 {s:"I-1.2", p:1, t:"Shear force and bending moment diagrams", re:S(/shear force diagram|bending moment diagram|\bsfd\b|\bbmd\b|contraflexure|load diagram|plot (their|the) variation|variation of (bending|shear)/), ex:S(/influence line|moving load|rolling|collapse|plastic/)},
 {s:"I-1.2", p:1, t:"Bending stresses and shear stress distribution in beams; beams of uniform strength", re:S(/bending stress|shear stress (at|in|distribution)|section modulus|simple bending|uniform strength|glued|safe allowable bending|channel section|permissible stress in channel|maximum safe uniformly distributed load|variations? of bending stress|hollow section is connected|tapering chimney|wind pressure of/), ex:S(/prestress|weld|bolt|plastic section|sewer/)},
 {s:"I-1.2", p:1, t:"Deflection of beams: Macaulay, moment-area, conjugate beam and unit load methods", re:S(/slopes? and deflections?|deflection (of|at|in) (the )?(beam|cantilever|pipe|free end)|maximum deflection|macaulay|moment.?area|conjugate beam|vertical and horizontal displacements?|deflection at the free end|maximum central deflection|free end .{0,30}limited to|quarter of a circle/), ex:S(/jet|settlement|prestress|pavement/)},
 {s:"I-1.2", p:1, t:"Torsion of shafts", re:S(/twisting moment|torsion|torque|angle of twist|hollow (circular )?shaft|solid circular shaft|\btwist\b/), ex:S(/viscos|cylinder rotates|vane shear|turbine/)},
 {s:"I-1.2", p:1, t:"Elastic stability of columns: Euler, Rankine and Secant formulae", re:S(/euler|secant formula|rankine'?s formula|buckling load|elastic stability|strut-testing|buckles/), ex:S(/web buckling/)},
 // I-1.3 Structural analysis
 {s:"I-1.3", p:1, t:"Analysis of pin-jointed trusses: forces in members", re:S(/truss|pin.?jointed|forces in (all )?(the )?members/), ex:S(/weld|bolt|connection|gusset|tension member|tie member|vertical member/)},
 {s:"I-1.3", p:1, t:"Castigliano's theorems, unit load method and consistent deformation", re:S(/castigliano|unit load method|vertical displacement of (joint|point)|vertical deflection of joint|strain energy|consistent deformation|virtual force/)},
 {s:"I-1.3", p:1, t:"Slope-deflection method", re:S(/slope.?deflection/)},
 {s:"I-1.3", p:1, t:"Moment distribution method", re:S(/moment distribution/)},
 {s:"I-1.3", p:1, t:"Rolling loads and influence lines", re:S(/influence line|moving (load|udl|uniformly)|moves over a simply supported|rolling load|(cross|traverse[sd]?|pass|over)( the)? (the )?(beam|girder|arch|bridge)|absolute maximum|wheel loads|series of three|five loads|20 m long simply supported girder/), ex:S(/pavement|axle load|axles/)},
 {s:"I-1.3", p:1, t:"Arches: three-hinged, two-hinged and fixed arches", re:S(/\barch(es)?\b|rib shortening/), ex:S(/archimedes/)},
 {s:"I-1.3", p:1, t:"Matrix methods: stiffness and flexibility", re:S(/stiffness matrix|flexibility matrix|matrix method|flexural stiffness|displacement method|force method/)},
 {s:"I-1.3", p:1, t:"Plastic analysis of beams and frames: plastic moment, shape factor, collapse load", re:S(/plastic (moment|analysis|bending|hinge|section modulus)|collapse load|shape factor|mechanism method|statical method|section modulus required|plastic moment mp/), ex:S(/class of section is plastic|assume the section is plastic/)},
 {s:"I-1.3", p:1, t:"Unsymmetrical bending and product of inertia", re:S(/unsymmetrical|product of inertia|principal axes|neutral axis.{0,30}angle/)},
 {s:"I-1.3", p:1, t:"Statically indeterminate beams and frames: propped cantilever, continuous beams, portal frames", re:S(/indeterminate|propped|continuous beam|fixed end moment|analyse (the )?(frame|structure|continuous)|rigid frame|portal frame|find the reaction at c|frame shown|tie rod/), ex:S(/pile|footing/)},
 // I-2.1 Structural steel
 {s:"I-2.1", p:1, t:"Bolted and riveted connections: bolt value, lap joints, HSFG bolts, brackets", re:S(/\bbolts?\b|rivet|high strength friction grip|hsfg|lap joint|bolt value|tack-bolted|efficiency of the joint|bracket|hanger connection|end plate/), ex:S(/pile|anchor bolt/)},
 {s:"I-2.1", p:1, t:"Welded connections: fillet and butt welds", re:S(/\bweld(s|ed|ing)?\b/), ex:S(/welded wire|steel plate girder is subjected to a maximum factored shear force of 2800/)},
 {s:"I-2.1", p:1, t:"Tension members: net area, block shear, angle ties", re:S(/tension member|effective net area|net area|block shear|tie member|tension in|ultimate tensile force|angles? are connected to the gusset|steel tension member/), ex:S(/prestress|soil/)},
 {s:"I-2.1", p:1, t:"Compression members: columns, struts, laced and battened columns", re:S(/laced column|batten|stanchion|built-up (steel )?column|slenderness|single angle strut|strut ISA|axial load capacity in compression|design compressive stress|compression member.{0,40}(steel|ISMB)/), ex:S(/pile|reinforced concrete|spiral|helical/)},
 {s:"I-2.1", p:1, t:"Steel beams, web buckling, bearing plates and moment capacity", re:S(/steel beam|ISMB|ISMC|laterally (supported|unsupported)|web buckling|bearing plate|design bending strength|plastic section|moment capacity|extra cover plate|section modulus required/), ex:S(/pile|hanger/)},
 {s:"I-2.1", p:1, t:"Plate girders and gantry girders", re:S(/plate girder|stiffener|gantry|overhead (travelling )?crane/)},
 {s:"I-2.1", p:1, t:"Factors of safety, load factors and limit state method for steel", re:S(/partial safety factor|load factor|limit state method.{0,30}steel|factors? of safety and load factors|working stress method and limit state/)},
 // I-2.2 Concrete and masonry
 {s:"I-2.2", p:1, t:"Concept of mix design", re:S(/mix design|mix proportion|revised mix|water.?cement ratio|durability factor|proportioning/)},
 {s:"I-2.2", p:1, t:"Working stress and limit state methods: principles and IS code provisions", re:S(/working stress method|principles of working|limit state of design of r|depth of neutral axis|stress-strain curves? for (concrete|reinforc)|balanced (section|failure)|derive the expression for determining the depth/)},
 {s:"I-2.2", p:1, t:"Flexural design of beams: rectangular, T and L sections, moment of resistance", re:S(/moment of resistance|t-beam|l-beam|flanged|singly reinforced|doubly reinforced|flexural reinforcement|beam of rectangular section|reinforced concrete beam|simply supported reinforced concrete beam|rectangular simply supported beam|cantilever beam \(300/), ex:S(/prestress|slab/)},
 {s:"I-2.2", p:1, t:"Shear, bond, anchorage, development length and lap splices", re:S(/shear reinforcement|stirrup|anchorage|development length|bond stress|lap splice|vertical shear reinforcement|curtail/)},
 {s:"I-2.2", p:1, t:"One-way and two-way slabs", re:S(/slab/), ex:S(/prestress|retaining|footing|pavement|stair|plate girder|raft|sluice/)},
 {s:"I-2.2", p:1, t:"Staircase slabs", re:S(/stair|dog-?legged|riser/), ex:S(/pipe/)},
 {s:"I-2.2", p:1, t:"RC columns: short and long columns, axial load with eccentricity, circular and helical columns", re:S(/(reinforced concrete|r\.?c\.?c?\.?) (circular |rectangular )?column|rectangular reinforced concrete column|circular column|helical|lateral ties|spiral|balanced failure|ground floor column|column section shown|transverse reinforcement in a reinforced|column (has|in a building)|design and detail the column/)},
 {s:"I-2.2", p:1, t:"Cantilever and counterfort retaining walls: design of stem, toe and heel", re:S(/stem|counterfort|toe slab|heel/), ex:S(/pile|steam/)},
 {s:"I-2.2", p:1, t:"Water tanks: rectangular and circular tanks resting on ground", re:S(/water tank|rectangular r\.?c\.?c?\.? water|tank walls|side walls of the tank/)},
 {s:"I-2.2", p:1, t:"Prestressed concrete: methods, systems, anchorages, losses and design for flexure", re:S(/prestress|pre-?tension|post-?tension|tendon|friction loss|parabolic cable|cable of cross-sectional area|loss of prestress/)},
 {s:"I-2.2", p:1, t:"Design of brick masonry as per IS codes", re:S(/design of brick masonry|load.?bearing wall|masonry column|IS 1905/)},
 // I-3.1 Fluid mechanics
 {s:"I-3.1", p:1, t:"Fluid properties: viscosity, surface tension, compressibility", re:S(/viscosity|viscous|shearing stress acting|newtonian|glycerine|cylinder rotates|surface tension|capillary rise|force is required to drag a very thin plate|velocity distribution for the flow of a newtonian/), ex:S(/soil|sewage|sludge|clay|aquifer/)},
 {s:"I-3.1", p:1, t:"Fluid statics: pressure, forces on plane and curved surfaces, buoyancy, manometry", re:S(/centre of pressure|total pressure force|submerged|buoyan|metacent|manometer|hydrostatic|vertical (isosceles )?triangular gate|rigid body having dimensions|weighs .{0,30} when submerged|inclined tube/), ex:S(/dam|soil/)},
 {s:"I-3.1", p:1, t:"Kinematics of flow: stream function, velocity potential, rotational and irrotational flow, continuity", re:S(/stream function|velocity potential|irrotational|rotational flow|flow is possible|constant stream function|csf|velocity components/)},
 {s:"I-3.1", p:1, t:"Bernoulli and energy equation, momentum equation and pipe flow problems", re:S(/bernoulli|energy equation|loss of head|head loss|pipe bend|\bbend\b|hgl|hydraulic grade|total energy line|egl|reservoirs?|siphon|jet (of|is|velocity|deflected)|nozzle|momentum equation|forces exerted by the pipe|tapering pipe|pipe (carries|line)|discharge through the pipe|vertical pipe|flow rate and find the direction|hagen|reynolds' number, pressure drop|draft tube|water flows from a to b/), ex:S(/turbine|sewer|water supply|treatment|soil/)},
 {s:"I-3.1", p:1, t:"Weirs, notches, orifices, venturi flumes and flow measurement", re:S(/\bweirs?\b|notch|orifice|venturi|flow meter|measure the discharge/)},
 {s:"I-3.1", p:1, t:"Navier-Stokes and Euler equations of motion", re:S(/navier|euler'?s equation of motion/)},
 // I-3.2 Dimensional analysis
 {s:"I-3.2", p:1, t:"Buckingham's pi-theorem and dimensionless parameters", re:S(/buckingham|dimensionless|dimensional analysis|pi.?theorem|non-dimension/)},
 {s:"I-3.2", p:1, t:"Similitude: model studies and prototype predictions", re:S(/similitude|model study|prototype|scale model|1:50 scale|1:10 scale|geometrically similar|model is tested/)},
 // I-3.3 Laminar flow
 {s:"I-3.3", p:1, t:"Laminar flow between parallel plates (stationary and moving)", re:S(/parallel plates|between two (fixed|horizontal)|plates are moving|plate 1|couette|maximum velocity of flow|laminar flow of oil/), ex:S(/soil|filter/)},
 {s:"I-3.3", p:1, t:"Laminar flow through a tube: Hagen-Poiseuille", re:S(/hagen|poiseuille|flow through (a )?(circular )?tube|laminar flow through|vertical pipe of 8 cm|3 cm diameter vertical pipe|1\.5 poise|1\.8 poise/)},
 // I-3.4 Boundary layer and turbulent pipe flow
 {s:"I-3.4", p:1, t:"Boundary layer on a flat plate: thickness, shear stress, drag, separation", re:S(/boundary.?layer|displacement thickness|flat plate|hydrodynamically (smooth|rough)|laminar sub-?layer|separation|friction drag|total drag|submarine|shear stress at the (middle|trailing)/)},
 {s:"I-3.4", p:1, t:"Drag and lift on bodies", re:S(/\bdrag\b|\blift\b|drag force|drag of|cylindrical chimney|exposed to a uniform \d+ km\/h wind/), ex:S(/dragline|drag a very thin/)},
 {s:"I-3.4", p:1, t:"Turbulent flow in pipes: velocity distribution, friction factor, HGL and TEL", re:S(/turbulent|friction factor|pipe friction|velocity distribution.{0,30}pipe|hgl and egl|draw the hgl/)},
 // I-3.5 Open channel flow
 {s:"I-3.5", p:1, t:"Uniform flow: Chezy, Manning, conveyance and channel design", re:S(/chezy|manning|uniform flow|conveyance|bottom slope|rectangular (laboratory )?(flume|channel)|triangular channel|trapezoidal (concrete )?lined channel|discharge in the channel/), ex:S(/sewer|soil|aquifer|canal is to be excavated/)},
 {s:"I-3.5", p:1, t:"Specific energy, critical depth and channel transitions", re:S(/specific energy|critical depth|specific force|smooth contraction|contracted width|channel bed is raised|transition|venturi flume|energy correction|momentum correction/)},
 {s:"I-3.5", p:1, t:"Hydraulic jump and rapidly varied flow", re:S(/hydraulic jump|sequent|\bjump\b|sluice gate (is|with)|conjugate depth/)},
 {s:"I-3.5", p:1, t:"Gradually varied flow: surface profiles and step method", re:S(/gradually varied|surface profile|mild|steep or critical|step method|control section|type 1, 2 and 3|\b[ms][123] (curve|profile)/), ex:S(/mild steel/)},
 // I-3.6 Hydraulic machines
 {s:"I-3.6", p:1, t:"Hydraulic turbines: Pelton, Francis and Kaplan; unit quantities and specific speed", re:S(/turbine|pelton|francis|kaplan|unit (discharge|power|speed)|specific speed|runner|draft tube|cavitation coefficient/)},
 {s:"I-3.6", p:1, t:"Principles of hydropower development", re:S(/hydropower|hydro.?electric|run.?off river|runoff river|pondage|load factor|power plant|generating capacity/)},
 // I-4 Geotechnical
 {s:"I-4", p:1, t:"Phase relations and index properties: void ratio, saturation, unit weights", re:S(/void ratio|degree of saturation|phase diagram|dry (unit weight|density)|water content|porosity|unit weight of (the )?soil|specific gravity of (soil )?(solids|particles|grains)|moist soil|field density|core.?cutter/), ex:S(/viscosity|\bpipe\b|flat plate|footing|raft/)},
 {s:"I-4", p:1, t:"Soil classification, gradation, particle size and consistency limits", re:S(/classif|sieve analysis|gradation|particle size|liquid limit|plastic limit|shrinkage (limit|ratio)|plasticity|flow (curve|index)|casagrande|suitability number|backfill material|consistency/), ex:S(/aggregate|sewage|building/)},
 {s:"I-4", p:1, t:"Soil structure and clay minerals", re:S(/clay mineral|soil structure|flocculat|dispersed|kaolinite|montmorillonite|illite|double layer/)},
 {s:"I-4", p:1, t:"Effective stress, pore water pressure and capillarity", re:S(/effective (stress|pressure)|pore (water )?pressure|neutral stress|capillar|total pressure|vertical effective/)},
 {s:"I-4", p:1, t:"Permeability and seepage: flow nets, quick sand, seepage pressure", re:S(/permeab|seepage|flow net|quick (sand|condition)|piping|boiling|hydraulic gradient|falling head|constant head|bottom heave|bursting|exit gradient|sand boiling|standpipe|discharge velocity/), ex:S(/concrete permeab/)},
 {s:"I-4", p:1, t:"Shear strength of soils: Mohr-Coulomb, triaxial, unconfined, direct and vane shear", re:S(/shear strength|mohr|triaxial|unconfined compressive|direct shear|vane shear|deviator|failure plane|undrained|consolidated drained|pore pressure parameter|cu test|cd test|major principal stress|minor principal stress|shearing strength/), ex:S(/pile|prestress|bearing capacity of a square|retaining wall|footing/)},
 {s:"I-4", p:1, t:"Compaction of soil: laboratory and field tests", re:S(/compaction|compacted|proctor|optimum moisture|borrow|embankment|\broller\b/), ex:S(/consolidation|pavement|dynamic/)},
 {s:"I-4", p:1, t:"Consolidation: theory, rate and settlement", re:S(/consolidat|compression index|coefficient of consolidation|preconsolidat|sand drains?|secondary compression|time factor|settle(s|ment) of (the )?(building|raft|clay|footing|structure)|normally consolidated|building settles|void ratio, delta e|change in void ratio/)},
 {s:"I-4", p:1, t:"Earth pressure and retaining walls", re:S(/earth pressure|retaining wall|rankine|coulomb|active (force|thrust|pressure)|passive|surcharge|tension crack|unsupported (cut|vertical)|smooth vertical back|backfill|lateral earth|vertical cut|stability of the retaining/), ex:S(/stem of the wall|counterfort/)},
 {s:"I-4", p:1, t:"Sheet piles, braced excavations and anchored walls", re:S(/sheet.?pile|anchored|braced (cut|excavation)|struts?.{0,30}peck|peck'?s|excavation/), ex:S(/single angle strut|strut-testing|euler/)},
 {s:"I-4", p:1, t:"Bearing capacity of soil: Terzaghi, field tests and plate load test", re:S(/bearing (capacity|pressure)|terzaghi|net ultimate|safe load|allowable (load|bearing)|plate load|footing/), ex:S(/pile|consolidation settlement|retaining|pavement|stem/)},
 {s:"I-4", p:1, t:"Settlement analysis of foundations", re:S(/settlement|settles/), ex:S(/pavement|sand drain|secondary/)},
 {s:"I-4", p:1, t:"Stability of slopes and earth dams", re:S(/slope stability|stability number|stability of slopes?|infinite slope|canal is to be excavated|side slope.{0,40}soil|earth dams?|factor of safety with respect to cohesion|rapid(ly)? emptied|rapid drawdown/)},
 {s:"I-4", p:1, t:"Subsurface exploration: boring, sampling, SPT and CPT", re:S(/boring|sampler|\bspt\b|standard penetration|subsurface exploration|soil investigation|borehole|cone penetration|pressuremeter|soil profile at a building site/)},
 {s:"I-4", p:1, t:"Foundation types, selection criteria and stress distribution under footings", re:S(/boussinesq|pressure bulb|stress (increment|increase)|vertical stress|westergaard|newmark|isobar|combined footing|raft|mat foundation|foundation (type|selection)|types? of foundation/)},
 {s:"I-4", p:1, t:"Pile foundations: capacity, group action and pile load test", re:S(/\bpiles?\b|pile group|pile load|friction piles|bearing piles|negative skin|well foundation|caisson|group efficiency|block failure|driving formula|hiley|is 2911|driven/)},
 {s:"I-4", p:1, t:"Ground improvement techniques", re:S(/ground improvement|vibroflotation|stone column|grouting|soil nailing|geosynthetic|reinforced earth|preloading|dynamic compaction|geotextile|dewatering|well.?point|lowering of (the )?water table|water table is to be lowered/)},

 // ================= PAPER II =================
 // II-1.1 Engineering materials
 {s:"II-1.1", p:2, t:"Stones, bricks and tiles: properties, tests and defects", re:S(/\bbricks?\b|\bstone\b|stones|\btiles?\b|clay bricks|efflorescence|frog|quarr/), ex:S(/stone bunds?/)},
 {s:"II-1.1", p:2, t:"Lime, cement and different types of mortars", re:S(/\bcement\b|\blime\b|mortar|pozzol|oxide|hydraulic cement|rapid hardening|quick setting|portland|\bist\b|\bfst\b|quicklime/), ex:S(/cement concrete pavement|cement concrete \(1|cement concrete pavement|tie bar|dowel/)},
 {s:"II-1.1", p:2, t:"Concrete: workability, admixtures, creep, shrinkage, aggregates, curing and durability", re:S(/workability|slump|admixture|accelerator|retarder|plasticizer|creep|curing|vibrat|segregation|bleeding|compressive strength of concrete|aggregate|bulking|durability of|concrete mix|proportioning concrete|water.?cement|tremie|deterioration of concrete|leaching|reinforcement necessary|plain cement concrete|properties of concrete|coarse aggregate|mortar content|cube strength|cylinder strength|bauschinger/)},
 {s:"II-1.1", p:2, t:"Ferro-cement, fibre reinforced concrete and high strength concrete", re:S(/ferro.?cement|fibre reinforced|fiber reinforced|high strength concrete|high performance|self.?compacting|polymer/)},
 {s:"II-1.1", p:2, t:"Timber: properties, defects and preservation", re:S(/timber|seasoning|preservative|plywood|wood\b/)},
 {s:"II-1.1", p:2, t:"Materials for low cost, mass and high-rise housing", re:S(/low cost housing|mass housing|high.?rise|prefab|selection of materials/)},
 // II-1.2 Construction
 {s:"II-1.2", p:2, t:"Masonry: bonds, construction detailing and strength", re:S(/masonry|english bond|flemish|brick work|rubble|ashlar|cavity wall|lintel|jamb|parapet|coping|cornice|brick thick|stone masonry|scaffold|formwork|form work|shoring|underpinning|damp.?proof|dampness|foundation trench/)},
 {s:"II-1.2", p:2, t:"Plastering, pointing, flooring, roofing, doors and windows", re:S(/plaster|pointing|flooring|\bfloor\b|\broof|pitched|eaves|rafter|\bdoor\b|window|ferro-cement tanks|formwork apart from|label the (terms|components)/), ex:S(/floor slab|flooring? of (a )?weir|weir floor|impervious floor|horizontal floor/)},
 {s:"II-1.2", p:2, t:"Common repairs in buildings", re:S(/repair|retrofit|rehabilit|guniting|shotcrete|cracks in/)},
 {s:"II-1.2", p:2, t:"Functional planning of buildings and building code provisions", re:S(/functional planning|bye-?laws|\bfar\b|floor area ratio|setback|plinth area|national building code|ventilation|planning of (a )?building|building code/), ex:S(/sewer|tunnel/)},
 {s:"II-1.2", p:2, t:"Estimating, specifications, rate analysis and valuation of property", re:S(/estimating|detailed estimate|approximate estimat|estimate of (cost|quantit)|specification (of|with|for)|rate analysis|analysis of rate|valuation|bill of quantities|\bboq\b|cost of a plot|real property|market (rate|value)|detailed analysis of rate/), ex:S(/width specifications|time estimate|rain ?gauge|precipitation|cement.{0,40}IST/)},
 {s:"II-1.2", p:2, t:"Construction equipment: earthwork and concreting machinery, selection and cost", re:S(/equipment|bulldozer|excavator|dragline|crane|sheep ?foot|roller|scraper|\bhoe\b|grader|dumper|hauling|operating cost|concrete mixer|machinery|percent swell|load factor/), ex:S(/locomotive|overhead travelling/)},
 // II-1.3 Planning and management
 {s:"II-1.3", p:2, t:"Construction schedules, bar charts, organisation, safety and quality assurance", re:S(/bar chart|gantt|schedule|organi[sz]ation of|quality (assurance|control)|\bsafety (measures|of workers|at site)|\bppe\b|\blabou?rs?\b|\bepf\b|welfare|work breakdown|resource (allocation|levelling|leveling)|milestone|\bcontractor|\bcontracts?\b|escalation|\bdpr\b|\btds\b|tendering stage|briefing stage/), ex:S(/completion time for the project/)},
 {s:"II-1.3", p:2, t:"CPM and PERT networks: critical path, float and slack", re:S(/\bcpm\b|\bpert\b|network|critical path|\bfloat\b|slack|activity|earliest|latest|three time estimates|expected time|a-o-a|a-o-n/), ex:S(/rail|wheel/)},
 {s:"II-1.3", p:2, t:"Cost optimisation (crashing) and resource allocation", re:S(/crash|cost slope|time.?cost|resource allocation|resource leveling|resource levelling|least cost|direct cost|indirect cost|masons/)},
 {s:"II-1.3", p:2, t:"Economic analysis: depreciation, present worth, interest and economic life", re:S(/depreciation|present worth|interest rate|economic life|equivalent annual|benefit.?cost|break.?even|replacement|discount rate|\bnpv\b|\birr\b|payback|cash flow|economic analysis|sinking fund|salvage|book value|diminishing balance/)},
 {s:"II-1.3", p:2, t:"Project profitability, BOOT approach, financial planning and toll fixation", re:S(/\bboot\b|\bboo\b|\bppp\b|toll|concession|profitab|infrastructure project|project finance|financial planning/)},
 // II-2.1 Surveying
 {s:"II-2.1", p:2, t:"Distance and angle measurement: chain, tape, compass and theodolite", re:S(/steel tape|chain|tape|slope correction|temperature correction|\bsag\b|theodolite|compass|local attraction|magnetic|fore bearing|back bearing|whole circle|bearing of|tacheometr|\bedm\b|total station|systematic errors|accidental errors/)},
 {s:"II-2.1", p:2, t:"Plane table surveying", re:S(/plane table|orientation of plane|resection|two.?point problem/)},
 {s:"II-2.1", p:2, t:"Traverse surveying: latitudes, departures and closing error", re:S(/traverse|latitude|departure|closing error|bowditch|transit rule|gale/)},
 {s:"II-2.1", p:2, t:"Levelling: level book, reduced levels, collimation and sensitivity of bubble tube", re:S(/levell?ing|level book|reduced level|\brl\b|staff reading|bubble|sensitivity|reciprocal|collimation|rise and fall|height of instrument|fly level|benchmark|bench mark|dumpy|staff readings/)},
 {s:"II-2.1", p:2, t:"Triangulation and base line", re:S(/triangulation|base.?line|intervisib|lighthouse|curvature and refraction|satellite station|trilateration|geodetic|well-conditioned/)},
 {s:"II-2.1", p:2, t:"Contouring and topographical maps", re:S(/contour|topographic|volume of water in the reservoir|characteristics of contours|map drawn/)},
 {s:"II-2.1", p:2, t:"Photogrammetry, remote sensing and GIS", re:S(/photogra|aerial|remote sensing|scale of (the )?photograph|stereo|parallax|flying height|\bgis\b|\bgps\b|spectral|\birs\b|satellite|sensor|relief displacement|overlap|photograph/)},
 {s:"II-2.1", p:2, t:"Setting out of curves and tunnel surveys", re:S(/setting out|curve ranging|tunnel|shift\b|transition curve.{0,40}shift|shaft at d|mechanically stabilized/), ex:S(/stabilized soil highway/)},
 // II-2.2 Railways
 {s:"II-2.2", p:2, t:"Permanent way: rails, sleepers, ballast, fastenings and creep", re:S(/\brails?\b|sleepers?|ballast|fish ?plate|\bcreep\b|permanent way|rail section|welded rail|\blwr\b|coning|wheels? of a railway|\bcms\b|track (components|section)/)},
 {s:"II-2.2", p:2, t:"Points and crossings, turnouts and diamond crossings", re:S(/turn.?out|points and crossings|crossing|switch|diamond|crossover|set of points|\blead\b|splice/), ex:S(/cross drainage|cross-section|cross regulator|crossing of the|level crossing of canal/)},
 {s:"II-2.2", p:2, t:"Geometric design of track: cant, gradient, curves and speed", re:S(/\bcant\b|cant deficiency|equilibrium cant|curve resistance|grade (resistance|compensation)|ruling gradient|negative cant|b\.?g\.? (track|yard|section)|m\.?g\.? track|(broad|metre|narrow|standard) gauge|types of gauges|choice of a gauge|booked speed|maximum sanctioned speed|super-?elevation.{0,30}(rail|track)/)},
 {s:"II-2.2", p:2, t:"Stations, yards, signals and clearances", re:S(/station|\byard\b|signal|interlocking|marshalling|siding|platform|semaphore|clearance/), ex:S(/proposed stations A and B|ground station|water treatment|gauging station|rain ?gauge|environmental clearance|traffic signal|intersection|statue|bar chart|aircraft|pavement/)},
 {s:"II-2.2", p:2, t:"Traction and train resistance", re:S(/locomotive|tractive|hauling capacity|train load|axle load.{0,30}tonn|haulage|resistances? which a locomotive|maximum load can it pull/)},
 {s:"II-2.2", p:2, t:"Track drainage and maintenance", re:S(/drainage of (a )?(railway )?track|track maintenance|ballast cleaning|packing|surface and sub-surface water can be removed from a railway/)},
 // II-2.3 Highway
 {s:"II-2.3", p:2, t:"Highway alignment and classification", re:S(/highway alignment|alignment of (a )?(highway|road)|ideal alignment|controlling the highway alignment|aligning a highway|classification of roads/)},
 {s:"II-2.3", p:2, t:"Geometric design: sight distance, curves, superelevation, widening and gradients", re:S(/sight distance|camber|super-?elevation|extra widening|vertical curve|summit|valley curve|horizontal (circular )?curve|set-?back|overtaking|stopping|design speed|geometric (design|features)|transition curve|ruling gradient|radius of horizontal curve|wheelbase|emergency braking/), ex:S(/rail|locomotive|cant/)},
 {s:"II-2.3", p:2, t:"Flexible pavement design: CBR, IRC 37, design traffic and axle loads", re:S(/flexible pavement|\bcbr\b|irc 37|design traffic|\bcsa\b|\bmsa\b|\bvdf\b|vehicle damage|esw?l|axle loads?|pavement composition|subgrade|\bdbm\b|\bwmm\b|\bgsb\b|lane distribution|msa|cumulative standard axle/)},
 {s:"II-2.3", p:2, t:"Rigid pavement design: joints, dowel bars, tie bars and slab thickness", re:S(/rigid pavement|dowel|tie bars?|radius of relative stiffness|cement concrete pavement|expansion joint|longitudinal joint|warping|westergaard|\bpqc\b|joint width/)},
 {s:"II-2.3", p:2, t:"Pavement construction: stabilised soil, WBM, bituminous works and CC roads", re:S(/stabili[sz]ed soil|\bwbm\b|bituminous|bitumen|stabili[sz]ation|marshall|soil.?cement|macadam|tack coat|prime coat|surface dressing|mechanically stabilized|construction of (a )?(road|pavement|highway)|bituminous concrete|reaction time/), ex:S(/aggregate for concrete/)},
 {s:"II-2.3", p:2, t:"Highway drainage and culverts", re:S(/side drains?|culvert|sub-?surface drain|highway drainage|drainage (in|of) highway|surface drainage|importance of drainage/)},
 {s:"II-2.3", p:2, t:"Pavement distresses, overlays and strengthening", re:S(/distress|overlay|benkelman|rutting|raveling|pothole|strengthening|reflection crack|maintenance of (highway|road)/)},
 {s:"II-2.3", p:2, t:"Traffic surveys and traffic planning: spot speed, O&D, speed-flow-density", re:S(/traffic survey|spot speed|origin and destination|o ?& ?d|desire line|floating car|speed and delay|speed-density|flow-density|journey speed|running speed|space-mean|time-mean|volume of traffic|speed limit|parking|accident|\bpcu\b|level of service|traffic stream|traffic volume|traffic study|maximum flow/)},
 {s:"II-2.3", p:2, t:"Intersections, rotaries, signal design, traffic signs and markings", re:S(/intersection|rotary|signal design|traffic signs?|markings?|weaving|channeli[sz]|roundabout|traffic signal/)},
 // II-3.1 Hydrology
 {s:"II-3.1", p:2, t:"Hydrological cycle and human influences on it", re:S(/hydrological cycle|hydrologic cycle|human actions that affect/)},
 {s:"II-3.1", p:2, t:"Stream flow measurement: velocity-area method, current meter, rating curve", re:S(/velocity.?area|stream gauging|current meter|rating curve|discharge in a small stream/)},
 {s:"II-3.1", p:2, t:"Precipitation: rain gauges, mean rainfall and rainfall analysis", re:S(/rain ?gauge|raingauge|rainfall|precipitation|optimum number|standard error|isohyetal|thiessen|intensity.?duration|storm|rain falls/), ex:S(/pavement/)},
 {s:"II-3.1", p:2, t:"Evaporation, transpiration, evapotranspiration and infiltration", re:S(/evaporat|transpiration|evapotranspiration|infiltration|phi.?index|horton|lysimeter|\bindex\b.{0,20}(phi|18)|abstraction/), ex:S(/consumptive use of water is|filter/)},
 {s:"II-3.1", p:2, t:"Runoff, hydrographs and unit hydrograph", re:S(/hydrograph|runoff|run-off|base.?flow|s-curve|synthetic unit|snyder|superposition|direct surface|rational|catchment|watershed|curve number|ordinates|basin lag|unit hydrograph/), ex:S(/flood routing/)},
 {s:"II-3.1", p:2, t:"Flood frequency analysis and design flood", re:S(/flood frequency|return period|recurrence|gumbel|log.?pearson|probability of|risk that|design flood|probable maximum|overtopped|coffer dam is designed to withstand the 25-year/)},
 {s:"II-3.1", p:2, t:"Flood routing: reservoir and channel routing, Muskingum", re:S(/routing|muskingum|storage outflow|level pool|kinematic flood/)},
 // II-3.2 Ground water
 {s:"II-3.2", p:2, t:"Aquifer properties: specific yield, storage coefficient, permeability, aquitards", re:S(/aquifer|aquitard|aquiclude|specific yield|specific retention|storage coefficient|transmissib|darcy|hydraulic conductivity|perched|artesian|ground ?water (table|flow)|unconfined|confined/), ex:S(/ground water table is at|ground water level/)},
 {s:"II-3.2", p:2, t:"Radial flow into wells: confined and unconfined conditions, drawdown and well loss", re:S(/drawdown|pumping well|observation well|tube.?well|open well|well (loss|development|screen|diameter|penetrat)|\bwell\b.{0,40}(pumped|aquifer|drawdown|penetrat|diameter)|a \d+(\.\d)? ?(cm|m) (diameter )?well|test well|specific capacity|radius of influence|thiem|cone of depression|discharge of a tube well|well in/), ex:S(/as well as/)},
 // II-3.3 Water resources
 {s:"II-3.3", p:2, t:"Ground and surface water resources, single and multipurpose projects", re:S(/multi-?purpose|single.?purpose|water resources|river valley project|allocation of water|surface water|resources of|irrigation project/)},
 {s:"II-3.3", p:2, t:"Reservoir storage capacity, losses and mass curve", re:S(/mass (inflow )?curve|storage capacity|reservoir capacity|dead storage|live storage|trap efficiency|reservoir losses|flow mass curve|yield of|capacity of a reservoir|useful life of the reservoir/)},
 {s:"II-3.3", p:2, t:"Reservoir sedimentation", re:S(/sediment|silting|reservoir sedimentation|reservoir life|probable life of the reservoir/), ex:S(/sludge|sedimentation (tank|basin)|settling/)},
 // II-3.4 Irrigation
 {s:"II-3.4(i)", p:2, t:"Water requirements of crops: consumptive use, duty and delta", re:S(/consumptive|\bduty\b|\bdelta\b|\bkor\b|crop|field capacity|wilting|water requirement|time factor|capacity factor|cropping pattern|intensity of irrigation|rabi|kharif|sugarcane/)},
 {s:"II-3.4(i)", p:2, t:"Irrigation methods, frequency and efficiencies", re:S(/irrigation (method|efficiency|frequency)|frequency of irrigation|sprinkler|drip|border|furrow|check basin|application efficiency|irrigate|infiltration capacity of soil|depth of water to be applied|average moisture content/)},
 {s:"II-3.4(ii)", p:2, t:"Canal distribution, capacity, losses and alignment", re:S(/canal (capacity|losses|alignment|distribution)|distributary|command area|design discharge of a canal|gross command|canal losses|alignment of (main|canal)|maintenance problems posed by irrigation canals/)},
 {s:"II-3.4(ii)", p:2, t:"Canal design: regime theory, Lacey, Kennedy, lined canals, critical shear", re:S(/lacey|kennedy|regime|silt factor|critical velocity|most efficient|best hydraulic|lined canals?|lined channel|trapezoidal|tractive force|critical shear|bed load|silt theory|open drain|safety ladders|expansive soils/)},
 {s:"II-3.4(iii)", p:2, t:"Water logging: causes, effects, control and salinity", re:S(/water.?logging|waterlogged|salinity|salini[sz]ation|reclamation|alkali|drainage coefficient|subsurface drain|tile drain/)},
 {s:"II-3.4(iv)", p:2, t:"Canal structures: regulators, falls, aqueducts, flumes and outlets", re:S(/head regulator|canal fall|aqueduct|super ?passage|cross regulator|\bescape\b|canal outlet|\boutlet\b|metering flume|cross drainage|silt excluder|silt ejector|\bfalls?\b|syphon|siphon aqueduct/), ex:S(/outlet zone|outlet of the tank|inlet and outlet zones/)},
 {s:"II-3.4(v)", p:2, t:"Diversion headworks: weirs, barrages, Khosla's theory and exit gradient", re:S(/diversion|head ?works?|weir (floor|across)|barrage|khosla|exit gradient|uplift|undersluice|divide wall|fish ladder|impervious floor|bligh|failure of weirs|causes of failure of weirs|difference between a weir and a barrage|weir across an alluvial/)},
 {s:"II-3.4(vi)", p:2, t:"Storage works: types of dams, gravity dam stability and earth dams", re:S(/\bdams?\b|gravity dam|earth(en)? dam|rock.?fill|arch dam|buttress|elementary profile|phreatic|mass-concrete dam|galleries|coffer dam|cracking of concrete in concrete gravity|modes of failure in gravity/), ex:S(/dampness|damp-proof/)},
 {s:"II-3.4(vii)", p:2, t:"Spillways and energy dissipation", re:S(/spillway|ogee|chute|siphon spillway|shaft spillway|stilling basin|energy dissipat|ski.?jump|cistern|hydraulic jump type/)},
 {s:"II-3.4(viii)", p:2, t:"River training works", re:S(/river training|guide bank|\bspur\b|groyne|bank protection|marginal bund|training works|afflux|meandering|cut.?off/)},
 // II-4 Environmental engineering
 {s:"II-4.1", p:2, t:"Water demand, population forecasting and design period", re:S(/per capita|demand|population|design period|incremental increase|peak hour|fire demand|fluctuation/), ex:S(/traffic|speed|equipment|hydrograph|market/)},
 {s:"II-4.1", p:2, t:"Impurities of water, analysis, waterborne diseases and potable water standards", re:S(/impurities|analysis of water|waterborne|water-borne|potable|water quality|drinking water|indicator organism|coliform|\bmpn\b|hardness|alkalinity|fluoride|arsenic|turbidity|bacteriological|nitrite|nitrate|e-coli|dissolved oxygen.{0,30}water quality|threshold odour|odou?r/)},
 {s:"II-4.2", p:2, t:"Coagulation, flocculation and sedimentation of water", re:S(/coagulat|flocculat|sedimentation|settling (tank|basin|zone)|alum|clarifier|tube settler|rapid mixing|jar test|surface overflow|settling velocity|stokes|particles at/), ex:S(/sewage|sludge|waste/)},
 {s:"II-4.2", p:2, t:"Filtration of water: slow, rapid and pressure filters; backwash", re:S(/\bfilters?\b|filtration|backwash|rapid sand|slow sand|pressure filter|filter (surface|medium)|uniform sand is used as a filter/), ex:S(/trickling/)},
 {s:"II-4.2", p:2, t:"Chlorination, disinfection, softening and removal of taste, odour and salinity", re:S(/chlorin|disinfect|break.?point|softening|lime.?soda|ion exchange|taste|desalination|reverse osmosis|aeration of water|iron removal|fluoride removal|residual chlorine|chlorine (dosage|demand)/)},
 {s:"II-4.3", p:2, t:"Sewerage systems: separate and combined, sewers and their design", re:S(/\bsewers?\b|sewerage|storm (water|sewage)|separate and combined|self.?cleansing|manhole|house connections?|domestic sewage|industrial waste|inverted siphon|velocity in (a )?circular sewer|sewage flow|variation of sewage flow/)},
 {s:"II-4.4", p:2, t:"Sewage characterisation: BOD, COD, solids, DO, nitrogen and TOC", re:S(/\bbod\b|b\.o\.d|\bcod\b|\bthod\b|\bubod\b|\bsolids\b|dissolved oxygen|oxygen sag|streeter|nitrogen|\btoc\b|oxygen demand|first order|deoxygenation|reaeration|nitrification|cbod|glutamic|glucose|glycine/)},
 {s:"II-4.4", p:2, t:"Standards for disposal of effluents into watercourses and on land", re:S(/standards? (of|for) disposal|disposal (in|into|on) (a )?(normal )?water ?course|effluent standards|self.?purification|dilution|river (water|is flowing|has an upstream)|disposal on land|discharged to a river/)},
 {s:"II-4.5", p:2, t:"Sewage treatment units: screens, grit chambers, sedimentation tanks", re:S(/sewage treatment|wastewater treatment|\bscreens?\b|grit|primary (settling|clarifier|sludge)|sedimentation tank is treating|sedimentation tank.{0,30}sewage|unit operations and processes|treat sewage|secondary reactor/)},
 {s:"II-4.5", p:2, t:"Biological treatment: trickling filters, activated sludge, oxidation ponds, septic tanks", re:S(/trickling|activated sludge|oxidation pond|stabili[sz]ation pond|septic tank|aerated lagoon|aeration tank|\bmlss\b|\bmlvss\b|\bsvi\b|rotating biological|sludge bulking|rising sludge|mcrt/)},
 {s:"II-4.5", p:2, t:"Sludge digestion, disposal and recycling of wastewater", re:S(/sludge|digest|imhoff|anaerobic|aerobic|recycling of waste|reuse of|digester|thickening|volume of sludge/)},
 {s:"II-4.6", p:2, t:"Solid waste: collection, disposal, landfills and long-term effects", re:S(/solid waste|landfill|\bmsw\b|municipal solid|compost|incinerat|leachate|waste management|segregation|transfer station|biomedical|e-waste|5 r|solid waste management rules|dumpsite|refuse/)},
 // II-5 Environmental pollution
 {s:"II-5", p:2, t:"Air pollution: pollutants, plume dispersion, control devices and emissions", re:S(/air pollut|pollutants?|\bstack\b|plume|lapse rate|dispersion|gaussian|greenhouse|climate change|ozone|acid rain|smog|particulate|\bnox\b|\bsox\b|sulphur dioxide|electrostatic|cyclone|scrubber|emission|fly ash|carbon monoxide|\blead\b.{0,30}cadmium|dumpsite fire|wind rose/)},
 {s:"II-5", p:2, t:"Environmental impact assessment, sustainable development, radioactive wastes and pollution control acts", re:S(/environmental impact|\beia\b|environmental clearance|sustainable development|radioactive|pollution control (act|board)|noise|mining|environment protection|scoping|screening|public consultation|thermal power plant|impact of mining/)}
];
