// Chemistry optional: syllabus sub-topics in syllabus order, with the words that tie a past question to each.
//   s    : the official item (I-1 ... II-7(v)) the sub-topic is filed under (see items.js)
//   re   : pattern tested against the question text (case-insensitive); written as a regex literal, stored as its source
//   ex   : a question that also matches this is NOT filed under the topic
//   refs : questions filed here by hand (year|paper|qno) because their text only says "the following reaction" and the structure is in the figure
//   fb   : true = fallback topic, used only for a question that no other topic claims
//   p    : 1 or 2 limits the topic to that paper (omit = both)
// A question can belong to several topics (UPSC often joins two ideas in one question).
// Re-run with:  node upsc-pyq-bank/tools/optional/chemistry/build-chemistry.js
const S = function(r){ return r.source; };
module.exports = [
 // ================= PAPER I =================
 {s:"I-1", p:1, t:"Uncertainty principle, wave function and particle in a box", re:S(/uncertainty|particle (confined|in a|of length)|one-dimensional box|rigid box|wave ?function|schr[oö]dinger|eigen ?(value|function)|operator|normali[sz]|de broglie|position and momentum|probability density|what is an orbital|degenerac|energy level|rydberg|hydrogenic|ground state/)},
 {s:"I-1", p:1, t:"Hydrogen atom: quantum numbers, radial functions and orbital shapes", re:S(/hydrogen atom|quantum number|radial|shapes? of .{0,20}orbital|angular (part|momentum)|\b[123][sp]\b|\b3d\b|electron spin|spin quantum|spin angular|spin-orbit|ionization energ|contours of|m_l|\bn, l\b|2p_?z/), ex:S(/molecular orbital|crystal[- ]field|ligand[- ]field/)},
 {s:"I-2", p:1, t:"Ionic bond, lattice energy and Born-Haber cycle", re:S(/lattice energ|lattice enthalpy|born[- ]hab|born-land|ionic (bond|compound|character|crystal)|fajan|polari[sz]/)},
 {s:"I-2", p:1, t:"Covalent bond, VSEPR/shapes, dipole moment, resonance and hybridisation", re:S(/dipole|resonance|hybridi[sz]|vsepr|shape of|geometry of|covalent|electronegativ|bond (angle|length|energy|strength)|valence bond|hydrogen bond|lewis|polar bonds|linear whereas|is linear|\bbent\b/), ex:S(/aromatic|carbocation|carbanion/)},
 {s:"I-2", p:1, t:"Molecular orbital theory, bond order and magnetic properties", re:S(/molecular orbital|\bLCAO\b|bond order|\bMO\b|paramagnetic|diamagnetic|dissociation energy|N₂⁺|O₂⁺|bond between the n atoms|electron is removed from/), ex:S(/crystal[- ]field|complex(es)? of|\[/)},
 {s:"I-3", p:1, t:"Crystal systems, unit cells, Bragg's law and X-ray diffraction", re:S(/unit cell|crystal system|miller|bragg|x-ray|diffraction|bravais|lattice (type|structure|parameter)|close pack|packing|hexagonal|cubic|crystal planes|radius ratio|NaCl|ZnS|CsCl|CaF|n ?λ ?= ?2d|sin ?θ/)},
 {s:"I-3", p:1, t:"Crystal defects, non-stoichiometry and semiconductors", re:S(/schottky|frenkel|defect|non-?stoichiometric|semi-?conductor|band (theory|gap)|doping|n-type|p-type|F-centre|colour centre/)},
 {s:"I-4", p:1, t:"Real gases, equation of state and critical phenomena", re:S(/real gas|van der waals|virial|critical (temperature|constant|volume|pressure|phenomen)|liquefaction|compressibility|boyle temperature|reduced equation|joule-?thomson/), ex:S(/inversion temperature/)},
 {s:"I-4", p:1, t:"Kinetic theory of gases: Maxwell speeds, collisions, effusion, viscosity and conductivity", re:S(/maxwell|root[- ]mean|mean free path|collision (number|frequency|diameter)|effusion|viscosity of .{0,12}gas|thermal conductivity|kinetic (theory|energy of)|most probable|average (speed|velocity)|equipartition|transport phenomen|transport propert|coefficient of viscosity|viscosity co-?efficient|boyle/), ex:S(/chain/)},
 {s:"I-5", p:1, t:"Liquid state: surface tension, capillary action, contact angle and Kelvin equation", re:S(/surface tension|capillar|contact angle|wetting|interfacial|kelvin equation|parachor|surface energy|viscosity of (a )?liquid|vapour pressure of (a )?(small )?droplet|droplet|straw|condense onto|onto glass/)},
 {s:"I-6", p:1, t:"First law: work, heat, internal energy, enthalpy and heat capacity", re:S(/first law|internal energy|enthalpy|heat capacity|\bC_?p\b|\bC_?v\b|adiabatic|isothermal.{0,40}work|calorimet|heat of (formation|reaction|combustion)|bond energ|kirchhoff|hess|\bwork\b|expansion|expands|pressure-volume|air temperature|rising clouds|tyre|compress|ΔH|ΔU|boiling point of mercury|valley/)},
 {s:"I-6", p:1, t:"Second law, entropy, free energy and Maxwell relations", re:S(/second law|entropy|free energy|gibbs|helmholtz|maxwell relation|carnot|fugacity|chemical potential|spontaneous|clapeyron|thermodynamic equation of state|\(∂|ΔG|ΔS|thermal equilibrium|zeroth|heat engine|reservoirs?|efficiency|temperature of a/)},
 {s:"I-6", p:1, t:"Joule-Thomson effect, equilibrium constant and third law", re:S(/joule-?thomson|inversion temperature|equilibrium constant|van'?t hoff (isochore|equation)|nernst heat|third law|absolute zero|residual entropy|degree of dissociation|Kp\b|Kc\b|criteria for equilibrium|reaction quotient|⇌|K_?eq|dissociated|ΔG°/), ex:S(/electrode|cell\b.{0,30}e\.?m\.?f/)},
 {s:"I-7", p:1, t:"Phase rule, one-component and binary phase diagrams, Clausius-Clapeyron equation", re:S(/phase (rule|diagram|equilibri)|clausius|eutectic|triple point|component system|partially miscible|critical solution|distillation|azeotrop|number of phases|boiling point diagram|steam distillation|distribution (law|coefficient)|nernst distribution|congruent|four-phase|phase system|sulphur system|sublime|sublimes|components and phases|phases are present|vapour pressure|melts/)},
 {s:"I-7", p:1, t:"Solutions: partial molar quantities, excess functions, colligative properties", re:S(/partial molar|partial molal|excess (thermodynamic|function|gibbs|enthalpy|volume|entropy)|colligative|raoult|henry|osmotic|ideal solution|freezing point|boiling point elevation|depression of|molality|mixing|van'?t hoff factor/), ex:S(/debye|ionic strength/)},
 {s:"I-8", p:1, t:"Strong electrolytes: Debye-Hückel theory, conductance and transport numbers", re:S(/debye|h[uü]ckel|ionic (strength|atmosphere|mobility)|conductance|conductivity|transport number|hittorf|kohlrausch|onsager|equivalent conductivity|molar conductivity|activity coefficient|electrolyte|electrolysis|ionic product|solubility product|ostwald dilution|current is passed|electrodes|coulomb|faraday|electrochemical reaction/), ex:S(/thermal conductivity/)},
 {s:"I-8", p:1, t:"Galvanic cells, e.m.f., Nernst equation, fuel cells and batteries", re:S(/galvanic|e\.?m\.?f|electrode potential|nernst equation|concentration cell|fuel cell|batter(y|ies)|electrochemical (series|cell)|standard (reduction )?potential|half[- ]cell|salt bridge|cell reaction|reference electrode|pH meter|calomel|glass electrode|lead storage|corrosion|E°|half-reaction/)},
 {s:"I-8", p:1, t:"Electrode processes, overpotential, double layer and electroanalytical techniques", re:S(/overpotential|overvoltage|double layer|current density|tafel|butler|polarogra|amperomet|voltammet|ion[- ]selective|charge transfer|exchange current|electroanaly|potentiomet|conductometric titration/)},
 {s:"I-9", p:1, t:"Rate equations: zero, first, second order and fractional order reactions", re:S(/order of (the )?reaction|rate (law|equation|constant)|first[- ]order|second[- ]order|zero[- ]order|half[- ]life|pseudo|integrated rate|rate of reaction|fractional order|initial rate|kinetic data/), ex:S(/consecutive|parallel|chain/)},
 {s:"I-9", p:1, t:"Complex reactions: reversible, parallel, consecutive, chain and branching chain reactions", re:S(/consecutive|parallel (elementary )?reaction|rate coefficients|opposing|reversible reaction|steady[- ]state|chain reaction|branching|explosion|rate[- ]determining|lindemann|unimolecular|enzyme|michaelis|autocatal|oscillat/)},
 {s:"I-9", p:1, t:"Temperature and pressure effects, fast reactions, collision and transition state theory", re:S(/arrhenius|activation energy|collision theory|transition state|activated complex|eyring|steric factor|pre-?exponential|stop[- ]?flow|relaxation|flash photolysis|temperature coefficient|fast reaction|entropy of activation|enthalpy of activation|frequency factor|salt effect|ionic strength on/)},
 {s:"I-10", p:1, t:"Photochemistry: light absorption, excited-state decay and quantum yield", re:S(/photochem|quantum (yield|efficiency)|fluorescence|phosphorescence|excited state|jablonski|lambert|beer|absorption of light|radiation|einstein|photon|photolysis|photosensitiz|chemiluminescence|intersystem|transmit|absorbance|molar absorpt|wavelength of light|incident light|monochromatic light|colou?r in|green light|daylight/)},
 {s:"I-11", p:1, t:"Adsorption isotherms: Langmuir, BET and surface area", re:S(/adsorption|adsorb|langmuir|\bB\.?E\.?T\b|freundlich|isotherm|surface area|physisorption|chemisorption|monolayer|gibbs adsorption/)},
 {s:"I-11", p:1, t:"Catalysis: heterogeneous catalysts and reaction mechanism on surfaces", re:S(/catalys|catalyt|catalyz|zeolite|haber|fischer-?tropsch|wilkinson|ziegler|hydroformylation|monsanto|wacker|poison|promoter|heterogeneous|surface reaction|langmuir-hinshelwood/), ex:S(/organometallic/)},
 {s:"I-12", p:1, t:"Metal ions in biology: ion transport, oxygen carriers, cytochromes and ferredoxins", re:S(/bio-?inorganic|haemoglobin|hemoglobin|myoglobin|hemerythrin|hemocyanin|cytochrome|ferredoxin|rubredoxin|na\+.{0,10}k\+ pump|ion[- ]transport|ionophore|biological system|metalloenzyme|metalloprotein|nitrogenase|carbonic anhydrase|vitamin b12|chlorophyll|porphyrin|oxygen[- ]uptake|oxygen[- ]binding|oxygen transport|across (the )?membrane|membrane transport|ion channel|photosystem|superoxide dismutase|blood|\bheme|dioxygen|hematin|iron-sulphur|iron-sulfur/)},
 {s:"I-13(i)", p:1, t:"Bonding in complexes: valence bond theory, crystal field theory, magnetism and spectra", re:S(/crystal[- ]field|ligand[- ]field|\bCFSE\b|\bCFT\b|valence bond theory.{0,60}(complex|octahedral|tetrahedral|square)|jahn-?teller|spectrochemical|magnetic (moment|property|properties|behaviou?r)|spin[- ]only|high[- ]spin|low[- ]spin|d-d|electronic spectr|tanabe|orgel|term symbol|charge transfer|\bt2g\b|\be_?g\b|paramagnet|splitting|nephelauxetic|racah|inner[- ]orbital|outer[- ]orbital|colou?r of .{0,30}complex|CuF|distort|UV-visible|number of peaks|complex ion/), ex:S(/organic|nmr/)},
 {s:"I-13(ii)", p:1, t:"Isomerism, nomenclature, stereochemistry, trans effect and stability of complexes", re:S(/isomer|iupac|nomenclature|chelate|polynuclear|trans[- ]effect|substitution.{0,30}square|square[- ]planar|stability constant|stability of (the )?complex|kinetic (inertness|lability)|labile|inert|thermodynamic stability|chirality|optical activity of|stereochemistry|ambidentate|geometry of .{0,30}complex|coordination (number|compound|isomer)|werner|irving|hard.{0,15}soft|hsab|relationship between a and b/), ex:S(/organic|carbonyl|pericyclic|sugar|glucose|alkene|\bnmr\b/)},
 {s:"I-13(iii)", p:1, t:"EAN rule, metal carbonyls, carbonyl hydrides and nitrosyls", re:S(/\bEAN\b|effective atomic number|18[- ]electron|carbonyl|nitrosyl|nitroprusside|carbonylate|metal hydride|hydrido/), ex:S(/aldehyde|ketone|C=O|organic/)},
 {s:"I-13(iv)", p:1, t:"Organometallic complexes: olefin, alkyne, cyclopentadienyl, oxidative addition, fluxional molecules, clusters", re:S(/organometallic|ferrocene|cyclopentadienyl|zeise|olefin complex|alkene complex|alkyne|arene|benzene.{0,30}chromium|dibenzene|oxidative addition|reductive elimination|insertion reaction|fluxional|metal[- ]metal|cluster|η|hapto|coordinative(ly)? unsaturat|wilkinson|vaska|metallocene|sandwich|Re2Cl8|Re₂|quadruple|\[Re/)},
 {s:"I-14", p:1, t:"Boranes, borazines, phosphazenes, silicates and silicones", re:S(/borane|diborane|borazine|borazole|phosphazene|silicate|silicone|polysilox|carborane|styx|wade|closo|nido|arachno|boron hydride|b2h6|b10h14|\(npcl2\)|polyphosphazene|aluminosilicate|clay|asbestos|zintl|boron nitride|orthosilicate|SiCl|PCl₅ ?\+ ?NH₄Cl/)},
 {s:"I-14", p:1, t:"Interhalogens, sulphur-nitrogen compounds and noble gas compounds", re:S(/interhalogen|polyhalide|\bClF|\bBrF|\bIF[357]|\bICl|noble gas|xenon|\bXe|\bKr|inert gas|sulphur[- ]nitrogen|sulfur[- ]nitrogen|S4N4|S2N2|\(SN\)x|polythiazyl|krypton|pseudohalogen|oxoacid|oxyacid|sulphur oxide|thionyl|sulphuryl|XeF|S₄N₄|S₂Cl₂|S₂N₂|SiH₃|inorganic benzene|octafluoro|tetrasulphur|peroxomono|sulphuric acid|NH₄NO₃/)},
 {s:"I-15", p:1, t:"Lanthanides and actinides: separation, oxidation states, magnetic and spectral properties", re:S(/lanthanide|actinide|lanthanoid|actinoid|f-block|\b[45]f\b|rare earth|lanthanide contraction|transuranium|uranium|thorium|europium|cerium|samarium|ytterbium|neodymium|gadolinium|plutonium|nuclear|Hf is placed|below zr|La to Lu|metallic radii|Ce³⁺|Yb³⁺/)},
 // ================= PAPER II =================
 {s:"II-1", p:2, t:"Aromaticity, anti-aromaticity, annulenes, azulenes, tropolones, fulvenes and sydnones", re:S(/aromatic|antiaromatic|anti-aromatic|annulene|azulene|tropolone|tropone|fulvene|sydnone|h[uü]ckel|cyclooctatetraene|cyclopentadienyl anion|tropylium|cyclopropenyl|benzenoid|delocali[sz]|resonance energy|homoaromatic|mesoionic|squaric|cyclobutenedione|cycloheptatrienyl|pKa|cyclopentadiene/), ex:S(/substitution|nitration/)},
 {s:"II-2(i)", p:2, t:"Methods of study of mechanisms: isotopes, crossover, trapping, stereochemistry, kinetic and thermodynamic control", re:S(/isotop|cross-?over|intermediate trapping|trapping|kinetic (and|vs|versus|control)|thermodynamic control|kinetic isotope|deuterium|labell?ing|energy of activation|energy profile|reaction coordinate|hammond|curtin|hammett|mechanism.{0,40}(study|determin|establish|evidence)|primary kinetic|secondary kinetic|tritium|13C|18O|k_?H\/k_?D|kH\/kD|possible intermediate|suspected intermediate|intramolecular mechanism|suitable experiment|\bLDA\b|kinetically|kinetic as well|thermodynamic product/), refs:["2023|2|1(b)(i)"]},
 {s:"II-2(ii)", p:2, t:"Reactive intermediates: carbocations, carbanions, free radicals, carbenes, benzynes and nitrenes", re:S(/carbocation|carbonium|carbo-?cation|carbanion|free radical|radical (intermediate|cation|anion|formation|stability|reaction)|radicals|carbene|benzyne|aryne|nitrene|reactive intermediate|intermediate.{0,30}(stability|geometry)|dichlorocarbene|carbenoid|simmons|ketene|enolate|nitrenium|KNH₂|NaNH₂|CHCl₃|bromobenzene/), refs:["2022|2|4(a)(ii)"]},
 {s:"II-2(iii)", p:2, t:"Substitution: SN1, SN2, SNi, neighbouring group participation, aromatic and heterocyclic substitution", re:S(/\bSN ?[12i]\b|SN1|SN2|SNi|nucleophilic substitution|neighbou?ring group|anchimeric|electrophilic (aromatic )?substitution|nucleophilic aromatic|SNAr|(pyrrole|furan|thiophene|indole).{0,50}(substitution|nitration|halogenation|sulphonation|acylation|reactivity|electrophil)|reactivity of (pyrrole|furan|thiophene|indole)|pyridine.{0,40}(nitration|substitution|electrophilic|nucleophilic)|quinoline.{0,40}(substitution|nitration)|nitration|sulphonation|friedel|vilsmeier|gattermann|ortho.{0,10}para|para.{0,10}direct|meta.{0,10}direct|orientation|activating|deactivating|aromatic (compound|ring|substitution)|walden|inversion of configuration|solvolysis|leaving group|acetolysis|rate of substitution|aqueous formic|chloroethyl|rates? of hydrolysis|bromocyclopent|cyclopentene oxide|2-butanol|2-butyl chloride|sodium azide|NaN₃|DMF|nitrotoluene|bromonitrobenzene|glycosyl|AgClO|NGP/), refs:["2021|2|2(c)(i)","2015|2|3(e)"]},
 {s:"II-2(iv)", p:2, t:"Elimination: E1, E2, E1cB, Saytzeff and Hofmann orientation, pyrolytic syn eliminations", re:S(/elimination|\bE1\b|\bE2\b|E1cB|saytzeff|zaitsev|hofmann|hoffmann|chugaev|cope elimination|acetate pyrolysis|pyrolytic|dehydrohalogenation|dehydration of|syn[- ]elimination|anti[- ]elimination|ester pyrolysis|xanthate|amine oxide|dehydration reaction|olefins expected|neomenthyl|fluoropentane/), ex:S(/pericyclic/), refs:["2018|2|6(c)","2021|2|3(a)(ii)","2021|2|3(c)(i)"]},
 {s:"II-2(v)", p:2, t:"Addition reactions: electrophilic addition to C=C and C≡C, nucleophilic addition to C=O, C≡N and conjugated systems", re:S(/addition (to|of|reaction)|markovnikov|anti-markovnikov|hydroboration|hydrohalogenation|halogenation of alkene|bromonium|michael|1,4-addition|1,2-addition|conjugate addition|conjugated (olefin|carbonyl|system)|nucleophilic addition|electrophilic addition|grignard|cyanohydrin|hydration of|α,?β-unsaturated|alpha,?beta|\benone|carbonyl compound.{0,40}react|oxymercuration|epoxid|cyclopropanation|ozonolysis|towards nucleophile|acrylate|(^|[^A-Za-z])O₃|norbornene|D–Br|bromohydrin|with HCl|with HBr|bromination/), ex:S(/pericyclic|diels|cycloaddition|metal|ligand|complex(es)? of/)},
 {s:"II-2(vi)", p:2, t:"Named rearrangements: pinacol, Hofmann, Beckmann, Baeyer-Villiger, Favorskii, Fries, Claisen, Cope, Stevens, Wagner-Meerwein", re:S(/rearrangement|pinacol|beckmann|baeyer[- ]villiger|favorskii|fries|claisen rearr|cope rearr|stevens|wagner|meerwein|hofmann (bromamide|rearr|degradation)|hoffmann (bromamide|rearr|degradation)|curtius|schmidt|lossen|wolff rearr|benzil|benzilic|dienone|semipinacol|migrat|neber|bamberger|sommelet|smiles|westphalen|shift of|1,2-shift|hydride shift|methyl shift|allyl phenyl ether|benzazocinium|ammonium|chloro.{0,20}cyclohexanone|COCH₂Cl/), refs:["2021|2|3(a)(i)"]},
 {s:"II-2(vi)", p:2, t:"Named condensations and reactions: aldol, Claisen, Dieckmann, Perkin, Wittig, Clemmensen, Wolff-Kishner, Cannizzaro, Sandmeyer and others", re:S(/aldol|claisen condensation|dieckmann|perkin|knoevenagel|wittig|witting|clemmensen|wolff[- ]kishner|cannizzaro|von richter|stobbe|benzoin|acyloin|fischer indole|skraup|bischler|napieralski|sandmeyer|reimer|tiemann|reformatsky|mannich|robinson annulation|darzens|gabriel|hell-?volhard|kolbe|riley|birch|oppenauer|meerwein-?ponndorf|haloform|diazonium|diazo coupling|azo coupling|pschorr|gomberg|hunsdiecker|arndt-?eistert|williamson|stork|enamine|malonic ester|acetoacetic|ethyl acetoacetate|β-hydroxy carbonyl|\(C₆H₅\)₃P|phenylhydrazine|name reaction involved|benzonitrile|CHCl₃/)},
 {s:"II-3", p:2, t:"Pericyclic reactions: electrocyclic, cycloaddition and sigmatropic shifts, Woodward-Hoffmann rules, FMO", re:S(/pericyclic|electrocyclic|cycloaddition|sigmatropic|diels[- ]alder|woodward[- ]hoffmann|frontier (molecular )?orbital|\bFMO\b|conrotatory|disrotatory|\[\s?[1-5]\s?,\s?[1-5]\s?\]|\[2\s?\+\s?[24]\]|\[4\s?\+\s?2\]|cope|claisen rearr|ene reaction|suprafacial|antarafacial|thermal(ly)? allowed|photochemically allowed|retro-?diels|correlation diagram|orbital symmetry|1,3-dipolar|1,5-pentadiene|allyl phenyl ether|bicyclic isomer|cycloocta-1,3,5-triene|cyclooctatriene|heat or light|cyclobutene|maleic anhydride|butadiene.{0,40}(maleic|diels|cycloaddition)|ergosterol|precalciferol|vitamin D|triene.{0,60}(heated|Δ|conrotatory|disrotatory|electrocycl|hν|thermal)/), refs:["2018|2|1(e)","2021|2|1(e)"]},
 {s:"II-4(i)", p:2, t:"Polymers: polyethylene, polystyrene, PVC, Teflon, nylon, terylene and rubber", re:S(/polymer|polyethylene|polythene|polystyrene|polyvinyl|\bPVC\b|teflon|ptfe|nylon|terylene|dacron|polyester|polyamide|rubber|vulcani[sz]|bakelite|monomer|copolymer|buna|neoprene|ziegler|natta|addition polymer|condensation polymer|tacticity|isotactic|degree of polymeri|resin|plastic|fibre|fiber|HDPE|LDPE|Perlon|caprolactam/)},
 {s:"II-4(ii)", p:2, t:"Biopolymers: structure of proteins, DNA and RNA", re:S(/protein|peptide|amino acid|dna\b|rna\b|nucleic|nucleotide|nucleoside|double helix|watson|base pair|genetic code|polypeptide|enzyme|carbohydrate|glucose|fructose|sucrose|starch|cellulose|glycogen|sugar|lipid|biopolymer|merrifield|amino acid sequence|peptide sequence|sequencing|base sequence|isoelectric|zwitter|denaturation|α-helix|helix|β-sheet|primary structure|secondary structure|edman|sanger/), ex:S(/organometallic|iron-sulphur|metalloprotein|cytochrome|haem|hemoglobin|myoglobin/)},
 {s:"II-5", p:2, t:"Reagents: OsO4, HIO4, CrO3, Pb(OAc)4, SeO2, NBS, B2H6, Na/liq. NH3, LiAlH4, NaBH4, n-BuLi, mCPBA", re:S(/OsO ?[4₄]|osmium|HIO ?[4₄]|NaIO ?[4₄]|periodic acid|CrO ?[3₃]|chromic|chromium trioxide|jones|\bPCC\b|collins|Pb\(OAc\)|lead tetra-?acetate|SeO ?[2₂]|selenium dioxide|\bNBS\b|N-bromosuccinimide|B2H6|diborane|hydroboration|liquid NH|liq(uid)?\.? ?NH|Na.{0,10}NH3|birch|LiAl ?H|lithium aluminium|NaBH|sodium borohydride|n-BuLi|butyl ?lithium|MCPBA|m-CPBA|peracid|peroxy|DDQ|DIBAL|lindlar|raney|wilkinson|BH₃|PhCOOOH|peroxybenzoic/), refs:["2015|2|8(c)","2014|2|8(d)","2021|2|8(a)(i)"]},
 {s:"II-6", p:2, t:"Organic photochemistry: excited states, singlet and triplet states, Norrish type I and II", re:S(/photochem|norrish|singlet (state|carbene|oxygen)|triplet (state|carbene)|photolysis|photo(reduction|oxidation|dimeri|isomeri|cycloaddition|sensiti)|excited state|paterno|b[uü]chi|di-?π|photo-?fries|jablonski|photon|hν|\bhv\b|irradiat|UV light|ultraviolet light|light-induced|barton|fluorescence|phosphorescence|photobromination|light intensity/), ex:S(/uv spectr|absorption max|λ ?max|woodward|nmr|\bir\b/), refs:["2021|2|6(c)(i)","2021|2|6(c)(ii)"]},
 {s:"II-7(i)", p:2, t:"Rotational spectroscopy: diatomic molecules, isotopic substitution and rotational constants", re:S(/rotational|microwave|moment of inertia|rotational constant|isotopic substitution|rigid rotor|rotation spectrum|reduced mass|pure rotation|bond length of/)},
 {s:"II-7(ii)", p:2, t:"Vibrational spectroscopy: IR, force constant, diatomic and triatomic molecules, functional group frequencies", re:S(/vibrational|infra-?red|\bIR\b|force constant|fundamental (frequency|vibration)|overtone|anharmonic|harmonic oscillator|stretching|bending|wavenumber|cm⁻¹|cm-1|normal modes?|raman|zero[- ]point|vibration|functional group|carbonyl (stretch|frequency|absorption)/)},
 {s:"II-7(iii)", p:2, t:"Electronic spectroscopy: UV-visible, n→π* and π→π*, Woodward-Fieser rules, charge transfer spectra", re:S(/\bUV\b|ultraviolet|uv-?vis|λ ?max|lambda max|woodward[- ]fieser|woodward rules|π ?→ ?π|n ?→ ?π|pi to pi|chromophore|auxochrome|bathochromic|hypsochromic|hyperchromic|hypochromic|red shift|blue shift|absorption (maximum|maxima|band|spectrum)|conjugated (diene|polyene|enone|carbonyl)|charge[- ]transfer|electronic (spectr|transition)|extinction coefficient|molar absorptivity|franck|solvent effect on .{0,20}spectr/), ex:S(/crystal field|d-d/)},
 {s:"II-7(iv)", p:2, t:"Proton NMR: chemical shift, spin-spin splitting and coupling constants", re:S(/\bnmr\b|n\.m\.r|chemical shift|coupling constant|spin[- ]spin|splitting|multiplet|triplet.{0,20}quartet|singlet.{0,20}doublet|δ ?\d|ppm|tms|tetramethylsilane|shielding|deshielding|magnetic resonance|13c|¹H|1H ?nmr|proton (nmr|signal|resonance)|integration|first[- ]order spectrum|karplus|diastereotopic|enantiotopic|nuclear spin/)},
 {s:"II-7(v)", p:2, t:"Mass spectrometry: parent peak, base peak, metastable peak and McLafferty rearrangement", re:S(/mass spectr|mass spectrum|parent peak|molecular ion|base peak|metastable|mclafferty|m\/z|fragmentation|isotopic peak|m\+|nitrogen rule|\bEI\b|electron impact|chemical ionization|fragment ion|\(M\+2\)|M\+2/)},
 // fallback: organic problems whose text only says "predict / complete / convert" (the structures are in the figure)
 {fb:true, s:"II-2(vi)", p:2, t:"Reaction problems: predict the product, reagent or mechanism of a conversion", re:S(/predict|product|convert|conversion|transformation|synthes|prepare|complete the|reagent|reaction|mechanism|identify|write the|name the|suggest/)},
];
