// Electrical Engineering optional: syllabus sub-topics in syllabus order, with the words that tie a past question to each.
//   s    : the official item (I-1 ... II-6) the sub-topic is filed under (see items.js)
//   re   : pattern tested against the question text (case-insensitive); written as a regex literal, stored as its source
//   ex   : a question that also matches this is NOT filed under the topic
//   refs : questions filed here by hand (year|paper|qno) because their text does not carry the words
//   fb   : true = fallback topic, used only for a question that no other topic claims
//   p    : 1 or 2 limits the topic to that paper (omit = both)
// A question can belong to several topics (UPSC often joins two ideas in one question).
// Re-run with:  node upsc-pyq-bank/tools/optional/electrical-engineering/build-electrical.js
const S = function(r){ return r.source; };
module.exports = [
 // ================= PAPER I =================
 {s:"I-1", p:1, t:"Network graphs, KCL/KVL, nodal and mesh analysis", re:S(/incidence matrix|tie-set|oriented graph|nodal|\bmesh\b|kirchhoff|\bKCL\b|\bKVL\b|dependent source|(find|calculate|determine|obtain).{0,60}(voltage|current|power).{0,70}(circuit|resistor|points?|terminals|network)|in the circuit (shown|given)|for the circuit (shown|given)|power loss in 1/), ex:S(/motor|transformer|transistor|darlington|diode|op-?amp|amplifier|transmission line|thyristor|\bSCR\b|converter|filter|alternator|oscillator|switching frequency|rectifier|induction|generator|two-port|wien|power factor|switch is|key k|input voltages|early voltage|logic equation|resistance Ro/)},
 {s:"I-1", p:1, t:"Network theorems: Thevenin, Norton, superposition, maximum power transfer", re:S(/thevenin|norton|superposition|maximum power transfer|maximum power|equivalent circuit across/)},
 {s:"I-1", p:1, t:"Transient analysis of RL, RC and RLC circuits", re:S(/transient|switch (is )?(closed|opened)|key k\d? is|at t\s?=\s?0|initial (current|charge|voltage)|capacitor has no charge|steady state is achieved|time (constant|domain expression)|current through the coil|opened at t/)},
 {s:"I-1", p:1, t:"Sinusoidal steady state, resonance and coupled circuits", re:S(/quadrature|phase relation between|resonan|impedances?|power factor|phasor|coupled circuit|mutual|\bj\d|capacitance of xc|steady[- ]state analysis|sinusoidal steady|reactive|series rlc|v-curves/), ex:S(/transmission line|synchronous|induction motor|transformer|transistor|op-?amp/)},
 {s:"I-1", p:1, t:"Balanced three-phase circuits", re:S(/three-phase|3-phase|3-φ|star-connected|delta-connected|Δ-connected|line currents|phase sequence/), ex:S(/motor|generator|alternator|inverter|rectifier|converter|transformer|cage|machine|induction|supply delivers|source is connected to an unbalanced/)},
 {s:"I-1", p:1, t:"Two-port networks", re:S(/two-port|two port|z-parameter|y-parameter|h-parameter|abcd|transmission and hybrid|y-parameters/)},
 {s:"I-2", p:1, t:"Continuous- and discrete-time signals, LTI systems, convolution and impulse response", re:S(/impulse response|convolution|\bLTI\b|linear time[- ]invariant|time-invariant|causal|difference equation|differential equation|signal x\(?t|sketch (and label )?the continuous|continuous-time signal|discrete-time (system|sequence)|sketch the (signal|continuous)|sequence x|unit impulse|energy of the signal|periodic waveform|waveform f|sketch.{0,40}signal|x\(?n\)? =|x\[n\]|output y\(?n\)? exists|represent the signal/), ex:S(/laplace transform of the (following )?periodic/)},
 {s:"I-2", p:1, t:"Fourier, Laplace and Z-transforms and transfer functions", re:S(/fourier|laplace|z-transform|z transform|DTFT|transfer function|dtft|inverse laplace|\bROC\b|region of convergence|partial fractions|spectrum|pole-zero/), ex:S(/amplitude modulat/)},
 {s:"I-2", p:1, t:"Sampling, DFT, FFT and discrete-time processing of analog signals", re:S(/sampl|\bDFT\b|\bFFT\b|aliasing|discrete-time systems|digitized/), ex:S(/sampling rate = |\bPCM\b|delta modulat|sampled uniformly/)},
 {s:"I-3", p:1, t:"Maxwell's equations, wave propagation and boundary conditions", refs:["2024|1|8(a)"], re:S(/maxwell|displacement current|plane wave|electric field|magnetic field|boundary|reflect|refract|dielectric|poynting|stokes|skin depth|propagation constant|conductivity|conducting|wave travel|potential gradient|slab|permittivity|magnetic flux|flux density|absorber|coax|permeab/), ex:S(/transmission line|smith chart|\bVSWR\b|standing wave/)},
 {s:"I-3", p:1, t:"Transmission lines: standing waves, impedance matching and Smith chart", re:S(/transmission line|smith chart|\bVSWR\b|standing wave|reflection coefficient|characteristic impedance|distortionless|electrical length|impedance matching|quarter|λ\/4|stub|lossless line|r-circles/)},
 {s:"I-4", p:1, t:"Diode, BJT, JFET and MOSFET: characteristics, biasing and equivalent circuits", re:S(/diode|transistor|\bBJT\b|JFET|MOSFET|bias|saturation current|reverse saturation|β\s?=|early (effect|voltage)|collector|emitter|schottky|zener|\bVBE\b|junction|darlington|rectifier circuit|clipp|clamp|differential pair|current mirror|\bCMOS\b/), ex:S(/thyristor|\bSCR\b|converter|inverter|chopper|digital|logic|flip|mux|multiplexer|\bgate\b|FM communication|AM signal|modulat|transformer|OPAMP|operational amplifier|regulated power|L-C load|uncontrolled diode rectifier|input bias current/)},
 {s:"I-4", p:1, t:"Amplifiers, frequency response and feedback", re:S(/amplifier|midband|break frequenc|bode|frequency[- ]response|corner frequency|cut-?off|differential (amplifier|mode)|\bCMRR\b|common[- ]mode|common-emitter|cascade|gain of|voltage gain|feedback|corner|slew|bandwidth of the|low pass filter circuit/), ex:S(/\bFM\b|\bAM\b signal|modulat|\bSNR\b|noise figure|noise power|receiver/)},
 {s:"I-4", p:1, t:"Op-amp circuits, filters, oscillators, wave-shaping and power supplies", refs:["2021|1|3(a)(ii)"], re:S(/op-?amp|operational|oscillat|filter|wien|integrator|summing|log(arithmic)? amplifier|inverting|instrumentation amplifier|voltage regulator|linear regulated|regulated power|wave[- ]?shaping|function generator|schmitt|relaxation|power supply|zener diode|waveform at points a and b|comparator/), ex:S(/FM demodulat|frequency modulat|envelope|\bPLL\b|phase-locked|matched filter|transformer|buck|dc-dc|d\.c\.-d\.c|converter|sideband|AM signal|pre-emphasis|superheterodyne|DSB-SC|sampled|continuous-time signal|noise is white|noise n\(t\) is white|vestigial/)},
 {s:"I-5", p:1, t:"Boolean algebra, minimisation, logic gates and logic families", refs:["2017|1|5(a)"], re:S(/boolean|karnaugh|k-map|minimi|prime implicant|\bNAND\b|\bNOR\b|logic (gate|circuit|equation|function|expression)|sum-of-products|\bSOP\b|\bTTL\b|\bCMOS\b gate|parity|truth table|logic family|logic circuit/)},
 {s:"I-5", p:1, t:"Combinational circuits: adders, code converters, multiplexers and decoders", re:S(/multiplexer|mux\b|decoder|adder|code converter|\bBCD\b|combinational|encoder|comparator|arithmetic circuit|error detector to check/)},
 {s:"I-5", p:1, t:"Sequential circuits: flip-flops, counters and shift registers", re:S(/flip[- ]?flop|counter|shift register|sequential|latch|state (diagram|transition)|master-slave|J-?K|synchronous (counter|sequential)|mod-?\d|D flip/)},
 {s:"I-5", p:1, t:"Timers, ADC/DAC, memories and programmable logic (ROM, PLA, FPGA)", re:S(/\bPLA\b|\bROM\b|\bFPGA\b|programmable logic|memory|\bADC\b|\bDAC\b|sample and hold|multivibrator|timer|555|analog-to-digital|digital-to-analog/)},
 {s:"I-6", p:1, t:"DC machines: characteristics, starting and speed control", re:S(/d\.?c\.? (shunt|series|motor|generator|machine|compound)|dc (shunt|series|motor|generator|machine)|armature (reaction|resistance|e\.?m\.?f)|separately excited|long shunt|commutat|ward-leonard|armature current|back e\.?m\.?f|armature conductors|torque and emf|brushes|field (current|circuit)/), ex:S(/chopper|rectifier|converter|firing angle/)},
 {s:"I-6", p:1, t:"Transformers: principles, regulation, efficiency and three-phase connections", re:S(/transformer|scott|voltage regulation|all[- ]day efficiency|open-circuit test|short-circuit test|kva.{0,30}(2400|1100|3300|110)|delta-star|autotransformer/), ex:S(/\bCT\b |current transformer|transmission|differential relay|protection|relay|generator and a|tap-changing/)},
 {s:"I-6", p:1, t:"Three-phase induction and synchronous machines", re:S(/induction (motor|machine)|synchronous (motor|generator|machine|condenser|reactance|impedance)|alternator|slip|squirrel|cage|salient|rotor|pull-?out|turbo|synchronous condens|cylindrical|torque angle|\bstarting torque|pole,? \d+ ?hp/), ex:S(/relay|protection|fault|three-phase generator rated 11|infinite bus|swing|stability|subtransient|short[- ]circuit current|circuit[- ]breaker/)},
 {s:"I-7", p:1, t:"Power semiconductor devices: thyristor, triac, GTO, MOSFET and triggering", re:S(/thyristor|\bSCR\b|triac|\bGTO\b|\bIGBT\b|snubber|di\/dt|latching|gate (drive|current|characteristic)|turn[- ]on|firing circuit|triggering/)},
 {s:"I-7", p:1, t:"Phase-controlled rectifiers and converters", re:S(/rectifier|full[- ]?wave|half[- ]?controlled|fully[- ]controlled|converter.{0,60}(bridge|phase|thyristor)|firing (delay )?angle|overlap|delay angle|bridge converter|phase[- ]controlled|source inductance|freewheel|battery of voltage/), ex:S(/diode rectifier circuit.{0,10}$/)},
 {s:"I-7", p:1, t:"Choppers, DC-DC converters and inverters", re:S(/chopper|buck|boost|dc-dc|d\.c\.-d\.c|inverter|pwm|switch[- ]mode|converter (circuit )?(shown|has)|duty (cycle|ratio)|ripple|step[- ]?(up|down)/), ex:S(/delta modulat/)},
 {s:"I-7", p:1, t:"Speed control of DC and AC motor drives", re:S(/speed control|drive|dynamic braking|regenerat|v\/f|vvvf|motor speed|speed of the motor|overhauling|plugging|variable[- ]speed|firing angle for rated|operating speed of the motor|motor.{0,40}(fed|supplied) (from|via|by)|torque and speed|developed torque|armature voltage/), ex:S(/transient/)},
 {s:"I-8", p:1, t:"Random variables, probability, random signals and noise", re:S(/random|probability|poisson|binomial|gaussian|noise|\bSNR\b|signal-to-noise|signal to noise|stationary|\bPSD\b|spectral density|white|statistical|variance|\bpdf\b|density function|distribution|noise figure|temperature of the attenuator|noise power/), ex:S(/delta modulat|\bPCM\b|coding|code word|huffman|entropy/)},
 {s:"I-8", p:1, t:"Amplitude modulation: DSB, DSB-SC and SSB, modulators and demodulators", re:S(/amplitude[- ]modulat|\bAM\b|\bDSB\b|\bSSB\b|\bVSB\b|vestigial|sideband|side band|modulation (index|factor|depth)|carrier|envelope detect|modulated (wave|signal)|percentage modulation|antenna current|mixer/), ex:S(/\bFM\b|frequency modulation/)},
 {s:"I-8", p:1, t:"Phase and frequency modulation, PLL, pre-emphasis and de-emphasis", re:S(/frequency modulat|phase modulat|\bFM\b|narrow ?band|pre-?emphasis|de-?emphasis|phase-locked|\bPLL\b|frequency deviation|slope circuit|demodulat|frequency demodulation|multiplier/)},
 {s:"I-8", p:1, t:"Radio receivers and signal-to-noise calculation", re:S(/superheterodyne|receiver|IF amplifier|image frequency|local oscillator|\bSNR\b|signal-to-noise|noise figure/)},
 // ================= PAPER II =================
 {s:"II-1", p:2, t:"Block diagrams, signal flow graphs, feedback and transfer functions", re:S(/block diagram|signal flow|mason|transfer function|sensitivity of the closed|closed[- ]loop|feedback (control )?system|unity (negative )?feedback|open[- ]loop|characteristic equation|control system|step (input|response)|overshoot|damping|settling time|peak time|rise time|dead time|time[- ]delay|steady[- ]state error|error coefficient|performance indices|undamped|(first|second)[- ]order (system|linear)|impulse response of a linear system|underdamped|position control|compensator network/), ex:S(/PCM|DPSK|convolutional|differential encoding|phase-locked|binary communication|LVDT|piezo|deflect|\bCRO\b|\bCRT\b|synchronous (generator|machine)|handshak|power system|transmission system|network shown in figure, draw a block diagram representing each circuit/)},
 {s:"II-1", t:"Stability: Routh-Hurwitz, root locus, Bode, polar and Nyquist", re:S(/routh|root[- ]locus|root loci|nyquist|bode|polar plot|gain margin|phase margin|stable|stability|asymptote|break-?away|break-?in|M-circles|constant magnitude/), ex:S(/power system|swing|transient stability|equal area|synchronous machine is connected/)},
 {s:"II-1", p:2, t:"Compensators and P, PI, PID controllers", re:S(/compensat|\blead\b|lag network|\bPID\b|\bPI\b|proportional|integral controller|derivative|controller/), ex:S(/series compensat|static var|shunt compens/)},
 {s:"II-1", p:2, t:"State-variable representation, controllability and observability", re:S(/state[- ]space|state[- ]variable|state model|state equation|state transition|controllab|observab|eigenvalue|state feedback|canonical form|state and output/)},
 {s:"II-2", p:2, t:"8085 architecture, registers, instruction set and addressing modes", refs:["2017|2|5(b)(ii)"], re:S(/8085|microprocessor|register pair|instruction|mnemonic|addressing mode|accumulator|stack pointer|\bMOV\b|\bADD\b|assembly|machine cycle|opcode|flag/), ex:S(/interrupt|interfac|8255|8253|\bDMA\b|timing diagram/)},
 {s:"II-2", p:2, t:"Timing diagrams, programming, interrupts and DMA", re:S(/timing diagram|interrupt|\bRST\b|\bSIM\b|\bRIM\b|\bDMA\b|handshak|clock cycle|T-states|execution time|program (to|for)|write an (8085|assembly)|loop will be executed|\bTRAP\b|\bINTR\b/)},
 {s:"II-2", p:2, t:"Memory and I/O interfacing, programmable peripheral devices", re:S(/interfac|memory chips|memory mapped|I\/O mapped|peripheral mapped|8255|8253|8254|8155|\bports?\b|decoding|memory (location|address)|\bMAR\b\b|\bbus\b|\bPPI\b|timer|interval timer/), ex:S(/OSI|internet|layer|p\.u\.|\bpu\b|power system|infinite bus|synchronous|load flow|bus admittance|differential encoding|alternators|steady-state power/)},
 {s:"II-3", p:2, t:"Error analysis and measurement of current, voltage, power, energy and power factor", re:S(/limiting error|probable error|uncertainty|accuracy|error caused|percentage error|wattmeter|energy meter|watt-hour|ammeter|voltmeter|moving[- ]coil|moving iron|shunt|multiplier|power factor of the|reading of each|ohmmeter|electrodynamometer|current transformer|ratio error|phase angle error|meter constant|measurement of power|instrument/), ex:S(/relay|\bCT\b ratio|differential/)},
 {s:"II-3", p:2, t:"Bridge measurements: R, L, C and frequency", re:S(/bridge|schering|maxwell|anderson|wien|Q[- ]meter|q factor|inductance of|capacitance and dissipation|balance condition|frequency counter|dielectric/), ex:S(/Wheatstone bridge is designed/)},
 {s:"II-3", p:2, t:"Electronic instruments: CRO, DVM, spectrum analyser, Q-meter", re:S(/\bCRO\b|oscilloscope|cathode|\bCRT\b|digital voltmeter|spectrum analy[sz]er|frequency counter|distortion|multimeter|ramp type|analog-to-digital|Q meter|signal conditioning|dynamic range|instrumentation amplifier/)},
 {s:"II-3", p:2, t:"Transducers: thermocouple, thermistor, LVDT, strain gauge, piezo-electric", re:S(/strain gauge|gauge factor|thermistor|thermocouple|\bLVDT\b|piezo|transducer|potentiometer|\bRTD\b|resistance temperature|displacement|temperature compensation|capacitive/)},
 {s:"II-4", p:2, t:"Transmission lines and cables: performance, parameters and cable grading", re:S(/transmission (line|system)|ABCD|A\s?=\s?D|nominal[- ]?π|nominal pi|charging|inductance of a single-phase|capacitance per phase|bundle|sub-?conductor|cable|insulation|grading|electric stress|equilaterally|ferranti|voltage regulation of a transmission|sending[- ]end|receiving[- ]end|surge impedance|travelling wave|wave is travelling|reflected by the load|distributor|tariff|load factor|diversity/), ex:S(/relay|protection|fault|breaker|binary|digital|modulat|VSWR|standing wave|characteristic impedance z0|smith|incremental|plants connected|synchronous machine|infinite bus|short-circuit capacit|piezo|oscilloscope|converter station|swing equation|power-angle/)},
 {s:"II-4", p:2, t:"Power transfer, per-unit quantities, bus matrices and load flow", re:S(/per[- ]unit (quantities|representation|system|values)|p\.u\.|\bpu\b|bus admittance|ybus|y-bus|zbus|impedance matrix|load flow|gauss[- ]seidel|newton|fast decoupled|primitive (impedance|admittance)|real and reactive power|power transfer|admittance matrix|tap-changing|transformer taps|power loss in the transmission/)},
 {s:"II-4", p:2, t:"Voltage control, power factor correction and economic operation", re:S(/economic|incremental|optimal|dispatch|penalty factor|loss (equation|coefficient)|fuel|voltage control|power factor correction|capacitors|synchronous condenser|automatic load frequency|load frequency|droop|governor|shunt capacitors|static var|\bSVC\b|saturated-reactor|compensator/), ex:S(/lead network|lag network|controller/)},
 {s:"II-4", p:2, t:"Symmetrical components and analysis of faults", re:S(/symmetrical component|sequence (network|impedance|reactance)|line[- ]to[- ]ground|single line|unsymmetrical|three-phase fault|3-phase fault|symmetrical fault|short[- ]circuit (current|capacity|MVA)|subtransient|fault current|fault level|solidly (grounded|earthed)|neutral reactance|neutral|grounding|earthing resistance|fault occurs|MVA of|short circuit occurs|open\. one conductor|one conductor of a three-phase line is open/), ex:S(/relay|differential protection|circulating current|breaker is rated|rated normal current|restriking|interrupt/)},
 {s:"II-4", p:2, t:"System stability: swing equation and equal-area criterion", re:S(/swing|equal[- ]area|critical clearing|stability|power-angle|power angle|inertia|\bH\s?=\s?\d|steady-state power limit|natural oscillations|infinite bus/), ex:S(/unity feedback|nyquist|routh|root|closed loop|bode/)},
 {s:"II-4", p:2, t:"HVDC transmission", re:S(/\bHVDC\b|DC link|converter station|valves used in \bHVDC\b|inverter operating in the constant extinction/)},
 {s:"II-5", p:2, t:"Overcurrent, differential and distance protection", re:S(/relay|buchholz|translay|differential (protection|relay)|percentage differential|distance (relay|protection)|overcurrent|over current|\bCT\b (ratio|secondary)|current transformer.{0,40}(relay|protect)|IDMT|circulating current|earth fault|core balance|harmonic restraint|protection scheme|is protected|to be protected|protection of|protection against/), ex:S(/no circulating current|line coding|LVDT|differential (amplifier|equation|encoding|pulse|capacitive)/)},
 {s:"II-5", p:2, t:"Circuit breakers: arc, restriking voltage and testing", re:S(/circuit[- ]breaker|\bCB\b|restriking|\bRRRV\b|\barc\b|interrupt(s|ing)|SF6|breaking|making current|oil circuit|rated normal current|short-time rating|magnetizing current of|magnetising current|current chopping|switchgear/), ex:S(/8085|microprocessor/)},
 {s:"II-5", p:2, t:"Solid-state, numeric and computer-aided protection of lines, buses, generators and transformers", re:S(/numerical|numeric relay|solid[- ]state|static (differential|relay)|computer aided|\bDSP\b|generator protection|bus ?bar|abnormal running|transformer protection|rectifier bridge amplitude/)},
 {s:"II-6", p:2, t:"PCM, DPCM and delta modulation", re:S(/\bPCM\b|pulse code|\bDPCM\b|differential pulse|delta modulat|\bDM\b|quantiz|slope overload|granular|companding|sampled uniformly|time-division|multiplex|nyquist rate|minimum sampling rate|line coding|\bNRZ\b|manchester|\bRZ\b/)},
 {s:"II-6", p:2, t:"Digital modulation: ASK, PSK, FSK, QAM and detection", re:S(/\bASK\b|\bPSK\b|\bFSK\b|QPSK|DPSK|BPSK|\bQAM\b|constellation|matched filter|bandwidth efficiency|power efficiency|error probability|probability of error|coherent|non-coherent|bit error|AWGN|signal space|gram-schmidt|orthonormal|bit rate|pulse transmission|digital modulation|signal detector|antipodal|binary (transmission|communication)/)},
 {s:"II-6", p:2, t:"Error control coding: linear block, cyclic, BCH and convolutional codes", re:S(/convolution(al)? (code|encoder)|linear block|hamming|parity check|generator (matrix|polynomial|sequence)|cyclic|\bCRC\b|\bBCH\b|syndrome|trellis|code (tree|word)|error (detection|correction|control)|coset|catastrophic|perfect code|GF\(/)},
 {s:"II-6", p:2, t:"Information measure, source coding and channel capacity", re:S(/entropy|information (content|measure|source|in a|rate)|huffman|shannon|source coding|channel (capacity|matrix)|mutual information|discrete memoryless|prefix|symbols x|joint probabilit|rate of information|capacity|bits per message|dots? and dashes?|code made up|messages? m1|probabilities of the symbols|coding efficiency/)},
 {s:"II-6", p:2, t:"Data networks and the 7-layer architecture", re:S(/\bOSI\b|\blayers?\b|internet model|\bTCP\b|protocol|\bnetwork\b|\bISO\b|data link|HTTPS|spanning tree|minimum weight/), ex:S(/transmission network|bus admittance|primitive|network shown|three-bus|network for|resistive|circuit/)},
 // ----- fallbacks, used only for a question no other topic claimed -----
 {s:"I-1", p:1, fb:true, t:"Circuit analysis (other)", re:S(/circuit|resistor|resistance|current|voltage|\bnetwork\b|capacitor|inductor/)},
 {s:"I-6", p:1, fb:true, t:"Electrical machines (other)", re:S(/motor|generator|machine|torque|speed/)},
 {s:"I-8", p:1, fb:true, t:"Communication systems (other)", re:S(/signal|modulat|spectrum|frequency/)},
 {s:"II-1", p:2, fb:true, t:"Control systems (other)", re:S(/system|controller|response|plot/)},
 {s:"II-4", p:2, fb:true, t:"Power systems (other)", re:S(/power|line|generator|voltage|transformer|MVA|kV/)},
 {s:"II-3", p:2, fb:true, t:"Measurement (other)", re:S(/meter|measure|instrument|resistance|error/)},
 {s:"II-6", p:2, fb:true, t:"Digital communication (other)", re:S(/code|bit|digital|source|channel/)},
];
