// Geography optional: syllabus sub-topics in syllabus order, with the words that tie a past question to each.
//   s    : the official item (I-P1 ... II-10) the sub-topic is filed under (see items.js)
//   re   : pattern tested against the question text (case-insensitive); written as a regex literal, stored as its source
//   ex   : a question that also matches this is NOT filed under the topic
//   refs : questions filed here by hand (year|paper|qno) because their text does not carry the words
//   fb   : true = fallback topic, used only for a question that no other topic claims
//   p    : 1 or 2 limits the topic to that paper (omit = both)
// A question can belong to several topics (UPSC often joins two ideas in one question).
// The "mark the ten places on the outline map" question (Paper II 1(a)) is filed with `refs` under the item of its first place.
// Re-run with:  node upsc-pyq-bank/tools/optional/geography/build-geography.js
const S = function(r){ return r.source; };
const LIST = [
 // ================= PAPER I: PHYSICAL GEOGRAPHY =================
 {s:"I-P1", p:1, t:"Earth's interior, continental drift, plate tectonics, isostasy and mountain building", re:S(/plate (tecton|boundar)|continental drift|isostasy|geosyncline|mountain (building|genesis|types|systems)|orogen|nappe|sea[- ]?floor spreading|palaeomagnet|himalaya.{0,20}rising|origin and evolution of the earth|interior of the earth|geomagnet|evolution of continents|truncated spurs|world mountains|kober/)},
 {s:"I-P1", p:1, t:"Volcanicity, earthquakes, tsunamis and pseudovolcanic features", re:S(/volcan|earthquake|tsunami|phreatic|pseudovolcanic|seismic|eruption|magnitude of earthquakes/)},
 {s:"I-P1", p:1, t:"Geomorphic cycles, denudation chronology, erosion surfaces and slope development", re:S(/pediplanation|peneplain|geomorphic cycle|geomorphological cycle|denudation chronology|erosion(al)? surface|slope (development|analysis|gradient)|davis|penck|periglacial|altiplanation|cycle of erosion|landscape is a function|landform development|stage\b.{0,20}process|solifluction|slope, altitude|slope and relief|periglacial/)},
 {s:"I-P1", p:1, t:"Channel morphology, fluvial landforms, coasts, caves and applied geomorphology", re:S(/channel|river|meander|helical|fluvial|avulsion|yazoo|coast|barrier island|sandspit|tombolo|speleothem|cave|karst|geological structure|economic geology|applied geomorphology|environmental geomorphology|flood plain|landform|geomorphology|seamount|guyot|geomorphic|stream basin|drainage divide|basket of eggs|drumlin/)},
 {s:"I-P2", p:1, t:"Heat budget, temperature, pressure belts and atmospheric circulation", re:S(/heat budget|insolation|temperature|pressure belt|atmospheric (circulation|stability|system)|tricell|general circulation|geostrophic|inversion|energy in the earth|balance of energy|forces which govern the air|barometric|anomalous/)},
 {s:"I-P2", p:1, t:"Winds, monsoons, jet streams, air masses, fronts and cyclones", re:S(/\bwinds?\b|monsoon|jet stream|air ?mass|front(ogenesis|olysis|s)\b|cyclone|anticyclone|thunderstorm|local winds|axis of dilation|pseudo monsoon|halloween|lightning/)},
 {s:"I-P2", p:1, t:"Precipitation, evaporation, hydrological cycle and climatic classification", re:S(/precipitation|evaporation|evapotranspiration|hydrolog|k[oö]ppen|thornthwaite|trewartha|climatic classification|classification of (world )?climate|world climate|weather and climate/)},
 {s:"I-P2", p:1, t:"Climatic change, global warming, urban climate and applied climatology", re:S(/climat(e|ic) change|global warming|urban climate|carbon (neutrality|sink)|greenhouse|WCRP|world climate research|climate migrants|el ni|pollution dome|ipcc|sea[- ]surface temperature|amoc|temperature and precipitation influence/)},
 {s:"I-P3", p:1, t:"Ocean floor topography and sea-level changes", re:S(/bottom topography|ocean floor|configuration of the|sea[- ]level change|sea level change|atlantic.{0,20}indian|pacific ocean floor/)},
 {s:"I-P3", p:1, t:"Temperature, salinity, waves, currents and tides", re:S(/salinity|ocean(ic)? (current|wave)|ocean waves|tides?\b|gyre|currents and (winds|climate)|wave of oscillation|winds and the currents|ocean current|currents of the|north atlantic/)},
 {s:"I-P3", p:1, t:"Marine resources, coral reefs, law of the sea and marine pollution", re:S(/marine (resource|pollution|energy|security)|coral|law of the sea|maritime zones|ocean ranching|oceans and their resources|exploitation and use of oceans|deep[- ]sea|resources of oceans|ocean.{0,10}resource/)},
 {s:"I-P4", p:1, t:"Soils: genesis, classification, profile, erosion and conservation", re:S(/\bsoils?\b|soil (profile|erosion|acidity|fertility|enrichment|horizon)|chernozem|sierozem|pedon|solum|humus|organic horizon|mineral horizon|azonal|intrazonal|degradation and conservation|land degradation|soil conservation|scarification/)},
 {s:"I-P4", p:1, t:"Plant and animal distribution, biomes, deforestation, social forestry and wildlife", re:S(/biome|rainforest|deforestation|floristic|newbigin|social forestry|agro-?forestry|wild ?life|gene pool|biological desert|genetic diversity|species|biodiversity|plants and animals|amensalism|biotic factor|desert|forest|vegetation|ecosystem approach|plants|wild plants/), ex:S(/ecosystem approach to environmental/)},
 {s:"I-P5", p:1, t:"Ecology, ecosystems and human ecological adaptation", re:S(/ecolog|ecosystem|human ecological|adaptation|deep ecology|shallow ecology|web of life|ecological (change|imbalance)|biophysical|carrying capacity/)},
 {s:"I-P5", p:1, t:"Environmental degradation, hazards, management, policy and education", re:S(/environmental (degradation|hazard|management|policy|education|issue|implication|problem)|hazard|disaster|flood|pollution|sustainable development|environmental conservation|carbon|PAVE|perception, attitude|use and throw|environment|mountaineer|resilience|dam/)},
 // ================= PAPER I: HUMAN GEOGRAPHY =================
 {s:"I-H1", p:1, t:"Evolution of geographical thought, paradigms and approaches", re:S(/paradigm|quantitative revolution|radical|behavioural|welfare (approach|geography)|humanistic|marxist|areal differentiation|regional synthesis|dichotomy|dualism|environmentalism|determinism|possibilism|perspectives in human geography|nature of geography|geographical systems|time-geography|sense of place|geographical thought|contested|eurocentric|spatial analysis|physical view of geographical space|systematic geography|compage|locational analysis|models and modelling|socio-spatial|space economy/)},
 {s:"I-H1", p:1, t:"Culture, language, religion, cultural regions and human development index", re:S(/cultur(e|al)|language|religion|secularis|human development|HDI|gender (equity|related)|folk culture|quality of life|social well-being|cultural identit|globali[sz]ation can|social capital|diaspora/), ex:S(/cultural regions of india/)},
 {s:"I-H2", p:1, t:"World economic development, resources, energy crisis and limits to growth", re:S(/economic development|world resources|energy crisis|limits to growth|resource|energy|stages of (economic )?growth|rostow|oil|critical minerals|development paradigm/), ex:S(/marine|ocean|soil|mineral deposit/)},
 {s:"I-H2", p:1, t:"Agriculture, food security, industries and world trade", re:S(/agricultur|food (security|and nutrition)|famine|stunting|wasting|nutrition|industr|manufacturing|trade|whittlesey|von th[uü]nen|weber|isodapane|isotim|footloose|transportation cost|least cost|polarisation|automation|protected cultivation|cultivation/), ex:S(/regional planning|growth pole|polarisation induced/)},
 {s:"I-H3", p:1, t:"Population: growth, distribution, migration, demographic transition and theories", re:S(/population|demograph|migrat|fertility|mortality|life expectancy|malthus|replacement|net reproductive|ageing|aging|aged|sex ratio|diaspora|transnational|stunting|refugee|NRR|social capital|displacement|migrant/), ex:S(/settlement|urban fringe|primate/)},
 {s:"I-H3", p:1, t:"Rural and urban settlements: patterns, hierarchy, morphology, urbanisation", re:S(/settlement|urban|town|city|cities|CBD|central business|rural-urban|rank[- ]size|primate|megalopolis|exopolis|conurbation|metropolitan|human settlements|urbanisation|slum/)},
 {s:"I-H4", p:1, t:"Regions, regionalisation, growth poles, regional imbalances and planning", re:S(/\bregion|regionali[sz]ation|growth (pole|centre)|perroux|boudeville|planning region|regional (imbalance|development|planning|disparit|synthesis)|land use planning|spatial inequalit|polarisation|in situ|thiessen|spatial unit|integration of the space|space economy/)},
 {s:"I-H5", p:1, t:"Location theories: Christaller, Losch, von Thunen, Weber and Rostow", re:S(/christaller|losch|l[oö]sch|central place|von th[uü]nen|weber|rostow|isodapane|isotim|least cost|location theory|theory of location|gravity model|complementary region/)},
 {s:"I-H5", p:1, t:"Population models, Marxian theory, Limits to Growth and systems analysis", re:S(/malthus|marxian|demographic transition|limits to growth|system analysis|systems analysis|neo-malthusian|stages of demographic/)},
 {s:"I-H5", p:1, t:"Geopolitical theories, heartland, rimland, boundaries and frontiers", re:S(/heartland|rimland|mackinder|spykman|boundar|frontier|geopoliti|pivot area|stop and go/)},
 // ================= PAPER II: GEOGRAPHY OF INDIA =================
 {s:"II-1", p:2, t:"Space relationship, structure, relief and physiography of India", re:S(/space relationship|structure and relief|relief features|physiograph|plateau|shiwalik|siwalik|karewa|himalaya.{0,30}(range|ecosystem)|gondwana|rock systems|geological structure|peninsular india|deccan|eastern ghats|north-western lava|chotanagpur|rock and mineral|cuddapah|dharwar/)},
 {s:"II-1", p:2, t:"Drainage system, rivers and watersheds of India", re:S(/drainage|river|rivers|watershed|east-flowing|west flowing|basin|indus|ganga|brahmaputra|shifting of river/), ex:S(/linking|inter-?linking|water sharing|water management board|satluj/)},
 {s:"II-1", p:2, t:"Monsoon, rainfall, cyclones, floods, droughts and climatic regions", re:S(/monsoon|rainfall|cyclone|western disturbance|flood|drought|climatic region|temperature and rainfall|dust storm|thunder|cloud ?burst|climate of india|el ni/), ex:S(/flood plain settlement/)},
 {s:"II-1", p:2, t:"Natural vegetation and soil types of India", re:S(/vegetation|soils? (of|in) india|black soil|volcanic soil|soil types|forest types|mangrove|biodiversity of the country|biological diversity|zonation/)},
 {s:"II-2", p:2, t:"Land, water, groundwater and mineral resources of India", re:S(/water (resource|scarcity|crisis|conservation)|groundwater|ground water|freshwater|mineral|coal|iron ore|bauxite|land resources|land use|ecological foot|critical minerals|resource utilization|utilisation of resources/), ex:S(/dispute|conflict|sharing|boards/)},
 {s:"II-2", p:2, t:"Energy, forest, wildlife, biotic and marine resources of India", re:S(/energy|solar|renewable|non-conventional|power|forest|wild ?life|tiger|vulture|biotic|marine resources|fisher|biodiversity conservation|man and wildlife|coral|blue economy|tribunal act/), ex:S(/pipeline|nuclear tourism/)},
 {s:"II-3", p:2, t:"Irrigation, institutional factors, land reforms and landholdings", re:S(/irrigation|institutional (factor|framework)|land (reform|tenure|holding)|landholding|command area|canal|fragmented|small and fragmented|seeds|fertili[sz]er|neem coated|agrarian/)},
 {s:"II-3", p:2, t:"Cropping pattern, productivity, Green Revolution, dry farming and agro-regions", re:S(/cropping|crop (diversification|residue)|agricultural (productivity|intensity|prosperity|diversification|regionali|sector|scenario)|green revolution|dry[- ]?(land )?farming|agro-climatic|agro-ecological|organic farming|millet|oilseed|plantation|protected cultivation|farmers’? suicide|food security|jute|cotton|sugar|crop|horticulture|fox nut|makhana|essential commodities|agricultur/), ex:S(/industr(y|ies) in india|jute mill|pharma/)},
 {s:"II-3", p:2, t:"Livestock, dairy, aquaculture, sericulture and poultry", re:S(/livestock|dairy|bovine|white revolution|aqua-?culture|sericulture|poultry|fisheries/)},
 {s:"II-4", p:2, t:"Industrial location: iron and steel, textile, jute, sugar, pharmaceutical, automobile and fertiliser", re:S(/iron and steel|steel plant|textile|jute|sugar|pharma|automobile|fertili[sz]er industry|cotton textile|mini steel|bokaro|industrial (complex|region|corridor|waste|growth|policy|house)|industries|industry|auto-hubs|foot-?loose|edible oil/), ex:S(/farmers|agricultur(e|al) (prosperity|sector)/)},
 {s:"II-4", p:2, t:"Industrial policy, multinationals, SEZs, start-ups and tourism", re:S(/new industrial polic|multinational|liberali[sz]|special economic zone|SEZ|start-?ups?|tourism|ecotourism|heritage|nautical|semi-?conductor|data centre|defence industry/)},
 {s:"II-5", p:2, t:"Transport networks: roads, railways, waterways, airways and pipelines", re:S(/road|rail|railway|waterway|airway|pipeline|river water transport|inland navigation|transport (network|and communication)|rapid transit|metro|public transport|transport system|sagarmala|port-led|ports?\b|seaports/), ex:S(/trade balance|balance of trade/)},
 {s:"II-5", p:2, t:"Ports, trade balance, trade policy and communication and space programme", re:S(/trade (balance|policy|pattern)|balance of trade|external trade|international trade|export|import|information technology|communication|space (programme|policy)|IRNSS|navic|satellite|satellite navigation|earth observation|digital divide|ICT|pattern of india’s trade|india’s trade/), ex:S(/pipeline network/)},
 {s:"II-6", p:2, t:"Society, tribes, languages, religions and cultural regions", re:S(/tribe|tribal|ethnic|linguistic|language|religio|racial|races|cultural region|culture|scheduled (castes|tribes)|minorit|historical perspective|folk house|indian society/), ex:S(/settlement morphology/)},
 {s:"II-6", p:2, t:"Population: growth, density, sex ratio, age structure, migration, health and policies", re:S(/population|demographic|sex[- ]ratio|age[- ]struct|literacy|workforce|work-force|migrat|fertility|health|life expectancy|dependency|population problems|human development|demographic dividend|stunting|wasting|ageing|international migrants|left behind/)},
 {s:"II-7", p:2, t:"Rural settlements: types, patterns and morphology", re:S(/rural settlement|rural-urban fringe|rural folk|settlements? (in|of)|human settlements|distribution of human settlements|rural landscape/), ex:S(/urban morphology/)},
 {s:"II-7", p:2, t:"Urban development: morphology, classification, conurbations, sprawl, slums and town planning", re:S(/urban|town|cit(y|ies)|metropolitan|conurbation|sprawl|slum|smart cit|peri-urban|ashok mitra|functional classification|urban heat|morphology of indian|city|planned city|nature of urbani|ncr|national capital/), ex:S(/ricardo/)},
 {s:"II-8", p:2, t:"Regional planning, Five Year Plans, rural development and Panchayati Raj", re:S(/regional (plan|development|disparit|imbalance)|five year plan|integrated rural|panchayat|decentrali[sz]ed planning|multilevel planning|multi-level planning|73rd|backward area|incentive oriented|grassroot|hill transport subsidy|ADP|aspirational|regional consciousness.{0,20}planning|regional planning/)},
 {s:"II-8", p:2, t:"Command area, watershed management, drought-prone, hill and island area development", re:S(/command area|watershed|drought-prone|hill area|island|desert|tribal area development|tribal sub-plan|border area development|job deficient|skill promotion|jal shakti|catch the rain/), ex:S(/aqua|coral reef/)},
 {s:"II-9", p:2, t:"Federalism, state reorganisation, inter-state issues and boundaries", re:S(/federal|state reorgani[sz]ation|re-organisation|new states|inter-?state|regional consciousness|border dispute|water (sharing|management board)|satluj|jammu and kashmir|linguistic regions and states|linguistic diversity/)},
 {s:"II-9", p:2, t:"International boundaries, terrorism, India's role and geopolitics of South Asia and the Indian Ocean", re:S(/international (boundar|border)|cross[- ]border|terroris|geo-?polit|geostrateg|geo-strateg|indian ocean|south asia|bhutan|nepal|sri lanka|bangladesh|china|sino|doklam|kalapani|quad|naxal|world affairs|maritime choke|south china sea|summits|indo-pacific|land boundary|border/)},
 {s:"II-10", p:2, t:"Environmental hazards: landslides, earthquakes, floods, droughts, epidemics and pollution", re:S(/landslide|earthquake|seismic|tsunami|avalanche|glacial lake|GLOF|flood|drought|epidemic|nipah|covid|pandemic|pollution|particulate|air quality|urban heat|disaster|hazard|solid waste|industrial waste|soil pollution|crop residue|stubble|quality of air|air during the winter/)},
 {s:"II-10", p:2, t:"Land use, desertification, deforestation, soil erosion and environmental management", re:S(/land use|desertification|deforestation|soil erosion|land degradation|environmental impact|environmental management|environmental degradation|sustainable|climate change|green (energy|architecture)|carbon|sustainable development|ecological|environment|paris agreement|overgrazing|great nicobar|land degradation/)},
 {s:"II-10", p:2, t:"Regional disparities, agrarian and industrial unrest, food security, linking of rivers and globalisation", re:S(/regional disparit|disparit(y|ies) in (development|economic)|agrarian|industrial unrest|food security|river linking|inter-?linking|linkage of rivers|globali[sz]ation|population explosion|farmers’? suicide|demographic dividend|naxal-affected|migration is the reflection|backward|startups/)},
 {s:"II-1", p:2, t:"Map question: places marked on the outline map of India (Paper II, Q1(a))", re:S(/outline map of india provided to you/)},
];
// the ten-places map question (Paper II 1(a)) belongs only to its own topic, whatever words its instruction line happens to contain
const MAPQ = S(/outline map of india provided to you/);
module.exports = LIST.map(function(t){ if(t.re === MAPQ) return t; t.ex = t.ex ? "(?:" + t.ex + ")|" + MAPQ : MAPQ; return t; });
