// For each official Mains GS line (in the order they appear in official-gs.json), the words that tie a past question to it.
// A question can belong to several lines. Run: node upsc-pyq-bank/tools/gs/build-gs.js [--check]
module.exports = {
 "GS Paper I": [
  /art\b|architecture|sculpture|temple|literature|painting|bhakti|sufi|buddhis|jain|gandhara|harappa|indus valley|vedic|ancient|medieval|mughal|cultur|heritage|dance|music|folk|festival|monument|inscription|\bveda|upanishad|maurya|gupta|chola|vijayanagara|rock[- ]cut|cave|stupa|script|theatre|cinema|puranas?|epic|ramayana|mahabharata|pallava|chalukya|sangam|ajanta|ellora|kushan|satavahana|harsha|delhi sultanate|sikh|guru|saint|poet|nalanda|taxila|museum|panipat|battle|chandella|art ?form|sculptor|artform/i,
  /british|colonial|east india company|1857|revolt|mutiny|\braj\b|viceroy|governor[- ]general|permanent settlement|ryotwari|mahalwari|drain of wealth|famine|renaissance|reform|brahmo|arya samaj|swadeshi|company rule|plassey|buxar|tipu|maratha|nineteenth|eighteenth|19th century|18th century|princely|subsidiary alliance|doctrine of lapse|education policy|macaulay|wood'?s despatch|railways|zamindar|peasant|tribal (revolt|uprising)|indigo|deccan riots|economic policies|dalhousie|bentinck|curzon|ripon|mountbatten|cripps|cabinet mission|wavell/i,
  /freedom struggle|national(ist)? movement|nationalis|gandhi|non-cooperation|civil disobedience|quit india|swaraj|khilafat|congress|moderate|extremist|\bbose\b|revolutionar|partition|independence|satyagraha|tagore|nehru|patel|ambedkar|tilak|gokhale|lal-bal-pal|rowlatt|jallianwala|dandi|salt|champaran|kheda|bardoli|simon commission|round table|poona pact|communal award|ghadar|home rule|indian national army|\bina\b|naval mutiny|bengal partition|vande mataram|annie besant|dadabhai|swadeshi|boycott|first world war and (the )?(indian|national)|women in the (freedom|national)/i,
  /post-?independen|integration of (the )?(princely )?states|princely states|reorgani[sz]ation of states|linguistic states|states reorgani|after independence|sardar patel|accession|partition and|rehabilitation of refugees|nehru'?s? (policy|era)|1947|constituent assembly|five[- ]year plan|green revolution|operation polo|goa|sikkim|hyderabad|junagadh|kashmir|new states|formation of (new )?states|smaller states/i,
  /world war|industrial revolution|russian revolution|french revolution|american (revolution|war|civil)|colonization|colonisation|decoloni[sz]ation|communis|capitalis|socialis|cold war|fascis|nazi|ottoman|suez|apartheid|league of nations|treaty of versailles|great depression|vietnam|korea|marx|enlightenment|redrawal|boundaries|unification of (germany|italy)|bolshevik|lenin|stalin|mao\b|chinese (revolution|communist)|japan'?s|meiji|latin america|african (colonies|nationalism)|imperialism|berlin wall|soviet|nato|marshall plan|bretton woods|united nations|world history|europe|arab|middle east|zionism|israel|palestine|iran|opium war|boxer|taiping|south africa|mandela|cuba|monroe|non-aligned|nasser|sukarno|ho chi minh|gorbachev|perestroika|glasnost|disintegration of (the )?(ussr|soviet)|brexit|european union|thirty years|napoleon|vienna|crimean/i,
  /salient features of indian society|diversity|indian society|caste|tribal|tribe|joint family|family|marriage|religio|multicultur|unity in diversity|kinship|rural|village|social structure|youth|ageing|elderly|migration|minority|dalit|honour killing|dowry|child marriage|live-in|old age|social change|sanskriti|westerni|modernity|tradition|patriarch|identity|ethnic|social (capital|stratification|mobility|justice)|class\b|middle class|culture of|north-?east|language|linguistic|syncretism|composite culture/i,
  /women|woman|gender|patriarch|feminis|population|demograph|sex ratio|poverty|urbani[sz]|slum|smart city|metropolit|housing|urban|child\b|children|unemployment|self[- ]help group|shg|empowerment of women|female|girl|maternal|fertility|birth rate|life expectancy|migration|ageing|youth|literacy|inequality|rural-urban|megacit|town planning|sanitation|waste management|mega ?cit|cities|\bcity\b|it hubs|aspirational district|human development|digital initiative|collaboration between government|socio-economic issues of development|sustainable growth|poor people/i,
  /globali[sz]ation|global(ization|isation)|effects? of global|westerni[sz]ation|consumerism|mcdonald|cultural homogeni|glocal/i,
  /empowerment|communal|regionalism|secular|reservation|dalit|scheduled (caste|tribe)|backward|affirmative|sub-?nationalism|insurgen|separatis|linguistic|language|religious (fundamental|conflict|extremism)|riot|violence|minority|identity politics|caste (system|and politics|violence)|untouchab|manual scaveng|social justice|inclusion|positive discrimination|ethno|autonomy|statehood|nativism|sons of the soil|migrant|hindutva|fundamentalism|intolerance|mob|disabilit|disabled|inclusive policy/i,
  /earth\b|continent|ocean|atmospher|climate|monsoon|cyclone|jet stream|el nino|la nina|plate tectonic|mountain|river\b|glacier|desert|landform|weather|rainfall|ice age|soil|biome|latitude|tropic|trade wind|temperature|current|tide|sea level|geomorph|erosion|weathering|volcan|earthquake|fold|rift|island|lake|delta|coast|erosion|himalaya|geograph|physical|cloud|precipitation|pressure belt|air mass|front|tornado|hurricane|typhoon|equator|polar|arctic|antarctic|ice cap|sahara|amazon|nile|ganga|mississippi|volga|rocks?\b|fjord|aurora|twister|tundra|straits?|isthmus|\bwinds?\b|\bloo\b|chinook|foehn|el[- ]nino|polar|ecologically fragile|non-farm|physiographic/i,
  /resource|mineral|coal|iron ore|petroleum|\boil\b|natural gas|industr|location|port\b|water resources|energy|hydro|solar|rare earth|fisher|agricultur|food|steel|textile|cotton|sugar|manufactur|shale|lithium|copper|bauxite|diamond|gold|uranium|thorium|oil refiner|tourism|special economic zone|cluster|corridor|auto|chemical|petrochem|jute|tea\b|coffee|rubber|locate|factors? (responsible|for)|raw material|forest produce|fishing|south china sea|global trade|indo-pacific|water treaty|indus water|water stress|trade|irnss|navigation/i,
  /earthquake|tsunami|volcan|cyclone|flood|landslide|drought|cloud ?burst|glacier|ice cap|water[- ]?bod|aral|lake|himalay|ice sheet|melting|sea level|flora|fauna|coral|shrinking|geophysical|critical geographical|permafrost|glacial|mount|eruption|seismic|fault|ring of fire|el nino|climate change|biodiversity loss|ecosystem|mangrove|wetland|depletion|iceberg|greenland/i
 ],
 "GS Paper II": [
  /constitution|amendment|basic structure|preamble|fundamental (right|dut)|directive|article \d|schedule|emergency|constituent assembly|judicial review|rights|citizenship|secular|federal|reservation|ninth schedule|sovereign|writ|habeas|doctrine|right to (privacy|information|education|life)|union territor|freedom of speech|speech and expression|hate speech|expression/i,
  /federal|centre[- ]state|union and (the )?states|state government|devolution|panchayat|local (government|bod)|73rd|74th|urban local|municipal|finance commission|gst council|inter-state|cooperative federalism|governor|special (category|status)|union territor|delhi|article 356|fiscal|decentrali|states? (and|vis)|autonomy|council|zonal|river water|water dispute|boundary dispute|local self|gram sabha|grassroot|village|district planning|metropolitan|sixth schedule|fifth schedule|tribal areas|north-?east|local institutions|functions, functionaries|decision-making and problem-solving|close to the source|subsidiarity/i,
  /separation of powers|dispute|tribunal|judicial|judiciary|court|lokpal|arbitration|redressal|grievance|ombudsman|legislature and (the )?executive|judicial activism|overreach|collegium|pendency|lok adalat|alternative dispute|mediation|checks and balances|rule of law|contempt|impeach/i,
  /compar.*(constitution|system|country|countries|uk\b|united states|us\b|america|britain|westminster|presidential|parliamentary|federal|semi-presidential)|other countries|indian constitution(al)? (with|and that)|with that of|british|american|french model|westminster|bicameral|parliamentary (system|form)|presidential (system|form)/i,
  /parliament|legislat|lok sabha|rajya sabha|speaker|bill\b|money bill|anti-defection|privilege|committee|question hour|ordinance|vidhan|assembly|council of states|house\b|zero hour|adjourn|disrupt|delimitation|session|vote on account|motion|whip|opposition|private member|dissolution|hung|coalition|bicameral|legislator|mp\b|mla|mlc/i,
  /executive|judiciary|ministr|cabinet|prime minister|president\b|governor|pressure group|civil society|\bpil\b|public interest litigation|supreme court|high court|bureaucra|department|niti aayog|planning commission|cag\b|cbi\b|intelligence|police|investigat|chief minister|council of ministers|attorney|solicitor|collegium|judge|tribunal|lobby|association|union|trade union|farmers'? (organi|protest)|interest group|think tank|media|ombudsman|judicial (appointment|accountab|independ)|elected|presidents? of/i,
  /representation of the people|\brpa\b|electoral|election|voting|\bevm|criminali[sz]ation of politics|disqualif|political part(y|ies)|\bnota\b|delimitation|model code|vvpat|campaign|candidate|polling|one nation one election|simultaneous|electoral bonds|funding of political|paid news|exit poll|anti-defection|voter|franchise|booth|party system|political part/i,
  /constitutional (post|bod|office|authorit)|comptroller|auditor|attorney general|advocate general|\bupsc\b|public service commission|election commission|finance commission|national commission|nhrc|human rights commission|sc\/st commission|cag\b|appointment|chief justice|governor|tribunal|lokpal|inter-state council|national commission for|backward classes|linguistic minorit|language|official language/i,
  /statutory|regulatory|regulator|sebi|trai\b|rbi\b|cci\b|competition commission|\bcic\b|information commission|\brti\b|right to information|consumer|\bngt\b|national green tribunal|nclt|quasi|authority|ombudsman|lokpal|\bcvc\b|vigilance|human rights commission|commission for|council|board\b|forum|appellate|irda|pfrda|cerc|cdsco|fssai|bureau|nhai|national (disaster|water)|lokayukta|data protection|ncw|ncpcr|ncsc|nclat|ibbi|insolvency/i,
  /polic(y|ies)|scheme|mission|yojana|programme|program\b|intervention|public policy|flagship|mgnrega|jan dhan|digital india|skill|startup|make in india|swachh|ayushman|\bpm-|national (mission|policy|programme)|initiative|government (policies|intervention)|implementation|design|delivery|dbt|direct benefit|aadhaar|targeting|leakage|convergence|monitoring|evaluation|outcome|welfare state|public goods|subsid|liberali[sz]ation|privati[sz]ation|governmental system/i,
  /\bngo|non-governmental|self[- ]help|\bshg|voluntary|civil society|charit|donor|philanthrop|\bcsr\b|corporate social|microfinance|stakeholder|development industry|foundation|third sector|community|cooperative|participat|social audit|aid\b|foreign contribution|fcra|volunteer|grassroots|social entrepreneur|trust/i,
  /vulnerable|welfare|scheduled (caste|tribe)|women|children|child|elderly|older|disabled|disability|divyang|minorit|transgender|differently|schemes? for|protection of|safeguard|domestic violence|child labour|trafficking|manual scaveng|tribal|dalit|senior citizen|orphan|beggar|migrant|refugee|backward|ncw|pocso|juvenile|violence against|sexual harassment|adivasi|nomadic|denotified|maternity|girl child|beti|sukanya|mahila/i,
  /health|education|school|universit|\bnep\b|literacy|nutrition|malnutrition|hospital|medical|human resource|skill|higher education|primary|\brte\b|right to education|ayushman|universal health|sanitation|drinking water|anganwadi|midday|mid-day|teacher|curriculum|vocational|digital divide|e-learning|online education|public health|disease|pandemic|covid|vaccin|tb\b|tuberculosis|insurance|doctor|nurse|medicine|pharma|ayush|mental health|nutrition mission|poshan|samagra|learning outcome|enrolment|dropout|gender gap|coaching|accreditation|ugc|aicte|nirf|human development/i,
  /poverty|hunger|food security|malnutrition|\bpds\b|public distribution|nutrition|mgnrega|\bbpl\b|multidimensional|starvation|\bnfsa\b|below poverty|ration|antyodaya|stunting|wasting|undernourish|global hunger|calorie|minimum wage|social security|pension|safety net|direct benefit|basic income|ultra poor|deprivation|livelihood/i,
  /governance|transparency|accountab|e-governance|citizen'?s? charter|\brti\b|right to information|digital|corruption|ombudsman|good governance|service delivery|lokpal|whistle|administrative reform|decentrali|social audit|public service|ict\b|common service|mygov|jan dhan|aadhaar|unique identification|digilocker|upi|open data|e-?kranti|national e-governance|grievance|sevottam|citizen|lokayukta|vigilance|probity|integrity|red tape|discretion|conflict of interest|gem\b|procurement|data protection|privacy/i,
  /civil service|bureaucra|administrat(or|ion)|\bias\b|public servant|steel frame|neutrality|political executive|district collector|civil servants|permanent executive|generalist|specialist|lateral entry|performance appraisal|morale|accountab|civil servant|anonymity|code of conduct|transfer|training|mission karmayogi|capacity building|sixth pay|administrative (culture|reform|leadership)/i,
  /neighbour|pakistan|china|bangladesh|nepal|bhutan|sri lanka|myanmar|maldives|afghanistan|saarc|bimstec|look east|act east|indus waters|teesta|border|doklam|kartarpur|gwadar|cpec|rohingya|tibet|indian ocean|neighbourhood first|string of pearls|ganga water|farakka|chabahar|iran|central asia|connectivity|bbin|belt and road|\bbri\b|line of actual|lac\b|loc\b|kashmir|siachen|water treaty|gujral|nuclear (deal|arms)|ladakh|galwan|dalai/i,
  /bilateral|regional|grouping|brics|quad\b|asean|saarc|bimstec|\bsco\b|g-?20|\bg-?7\b|\bwto\b|\bimf\b|opec|apec|\bnam\b|non-aligned|european union|\beu\b|agreement|treaty|india-?(us|usa|japan|russia|france|israel|uae|australia|africa|central asia|china|pakistan|bangladesh)|summit|indo-pacific|ibsa|rcep|cptpp|i2u2|malabar|trade (deal|agreement)|free trade|\bfta\b|strategic partnership|plurilateral|minilateral|mercosur|african union|commonwealth|gulf|west asia|bay of bengal|mekong|ganga|\bbbin\b|cepa|comprehensive|nuclear suppliers|nsg|mtcr|wassenaar|australia group|npt|ctbt|paris|cop\b|unfccc|isa\b|international solar/i,
  /diaspora|developed (and|&) developing|us policy|h-1b|trump|biden|brexit|sanction|trade war|immigration|protectionis|energy security|gulf|west asia|middle east|usa|united states|american|china'?s|russia|ukraine|afghanistan|taliban|iran|israel|palestine|syria|paris|climate (finance|negotiation)|north-south|technology transfer|patent|tariff|visa|remittance|nri|pio|oci|policies and politics|foreign policy|geo-?politic|strategic autonomy|multipolar|unipolar|containment|oil (price|supply)|currency war|dollar|china-?us|pivot|america first|decoupling|supply chain|semiconductor|data localisation|digital (trade|sovereign)|africa|oppressed|marginalised nations|asia'?s growth/i,
  /united nations|\bun\b|security council|\bunsc\b|\bwho\b|world bank|\bimf\b|\bwto\b|unesco|unicef|\bicj\b|international court|\bilo\b|\bfao\b|\bunep\b|\biaea\b|\bnsg\b|\bmtcr\b|nato\b|interpol|international (institution|organi[sz]ation|agenc|fora|forum|criminal)|world trade|bretton|\badb\b|\baiib\b|\bndb\b|brics bank|unhrc|human rights council|\bunfccc\b|\bicc\b|\bunctad\b|\bundp\b|\bunhcr\b|world economic forum|\bwef\b|\bfatf\b|\boecd\b|\bg-?20\b|\bg-?77\b|\bunga\b|general assembly|peacekeeping|\bicao\b|\bimo\b|\bitu\b|\bwipo\b|\bwmo\b|\bunido\b|multilateral|global governance|veto|reform of (the )?(un|security council)|permanent (member|seat)|mandate|structure/i
 ],
 "GS Paper III": [
  /\bplan(ning)?\b|indian economy|economic (growth|development|survey|slowdown|crisis|policy)|\bgdp\b|\bgnp\b|employment|unemployment|\bjobs?\b|jobless|resource mobili[sz]ation|capital formation|savings|inflation|monetary|banking|\bnpa|recession|demonetis|growth rate|informal sector|labou?r (force|market|intensive|law)|income|current account|balance of payments|rupee|exchange rate|stock market|credit|financial (sector|stability|market)|care economy|productivity|wage|gig|digital economy|forex|crude|potential output|human development/i,
  /inclusive|inequality|financial inclusion|poverty|income distribution|exclusion|jan dhan|vulnerable|marginali[sz]ed|rural-urban|regional (disparit|imbalance)|gender (gap|budget)|social sector|welfare|growth and (equity|inclusion)|trickle|empowerment|equity|distribut/i,
  /budget|fiscal deficit|\bfiscal\b|\bfrbm\b|expenditure|subsid|\btax|\bgst\b|public debt|deficit|revenue|appropriation|outcome budget|zero[- ]based|gender budget|finance bill|\bcess\b|direct tax|taxation|borrowing|capital expenditure|off-budget|fiscal consolidation|finance commission|devolution|vote on account|subvention|disinvestment|tax (buoyancy|base|gap|evasion|avoidance)|black money|gaar|income tax|corporate tax|customs|excise|economic survey/i,
  /crop|cropping|irrigation|agricultur|\bfarm|mandi|\bapmc\b|marketing|storage|warehous|cold chain|e-?nam|e-technology|kisan|horticultur|drip|watershed|dryland|soil health|fertili[sz]er|\bseed|organic|millets?|pulses|oilseed|rain-?fed|green revolution|farmer|aquaculture|fisher|livestock|agri|contract farming|farm laws|agri-?tech|precision|natural farming|zero budget|crop insurance|pmfby|credit|kcc|cooperative|fpo\b|farmer producer|agro-?climatic|monsoon|water (use|productivity)|per drop|sugarcane|cotton|rice|wheat|paddy|stubble|crop diversification|food grain|productivity|yield|second green|evergreen|bt\b|gm crops?|biofortif/i,
  /subsid|\bmsp\b|minimum support|public distribution|\bpds\b|buffer|food security|technology mission|animal|livestock|dairy|milk|cattle|poultry|food corporation|\bfci\b|\bnfsa\b|food ?grain|procurement|fertili[sz]er|urea|nutrient based|direct benefit|farm loan|waiver|price (support|stabili)|\bpss\b|bhavantar|pm-?kisan|input|power subsid|wto.*(peace clause|agricultur)|domestic support|stock ?holding|operation greens|cold storage|economics of animal|fisheries|meat|blue revolution|white revolution|pashu|rashtriya gokul/i,
  /food processing|supply chain|processing industr|agro[- ]?based|cold chain|mega food|post-harvest|wastage|value addition|upstream|downstream|packaging|food parks?|agro-?processing|export of (food|agri)|fssai|food (safety|standard)|perishable|logistics|farm to fork|contract farming|retail|fdi in (retail|food)/i,
  /land reform|land (record|holding|tenure|acquisition|lease|ceiling|consolidation|titling|bank|use|market|alienation|pooling|rights)|zamindari|tenanc|bhoodan|digiti[sz]ation of land|land and|agrarian|sharecropp|bhumi|rehabilitation and resettlement|right to fair compensation|forest rights|vested/i,
  /liberali[sz]ation|industrial policy|industrial growth|\bmsme|small (scale )?industr|manufactur|make in india|\bsez\b|special economic|\bfdi\b|foreign direct|reform|deregulat|1991|licen[cs]e|disinvest|privati[sz]ation|ease of doing|industrial corridor|competition|startup|textile|steel industr|public sector|pli\b|production[- ]linked|national manufacturing|aatma?nirbhar|globali[sz]ation|new economic policy|economic reforms|foreign investment|multinational|trade liberal|tariff|import substitution|export promotion|industrial (location|cluster|relocation|sickness|development)|capital goods|automobile|pharmaceutical|electronics|mining|labour (law|code|reform)|ibc|insolvency|exit policy|crony|monopoly/i,
  /infrastructure|energy|\bport|\broad|airport|railway|highway|sagarmala|bharatmala|logistics|power (sector|generation|plant|distribution)|electricity|renewable|solar|nuclear|\bcoal\b|\bppp\b|public-private|urban transport|metro|shipping|inland waterway|dedicated freight|udan|smart grid|transmission|hydro|wind|gas|pipeline|petroleum|green hydrogen|battery|electric vehicle|\bev\b|telecom|broadband|digital infrastructure|smart cit|water (supply|infrastructure)|sanitation|housing|toll|nhai|bridge|tunnel|airlines|aviation|rail|bullet train|freight|multimodal|gati shakti|connectivity|rural roads|pmgsy|\bdiscom|ujwal|transmission|grid|storage|lng|refiner|bio-?fuel|ethanol|national infrastructure pipeline|\bnip\b/i,
  /investment model|\bppp\b|public[- ]private|build[- ]operate|\bboot\b|\binvit\b|hybrid annuity|infrastructure investment|\bvgf\b|viability gap|\bfdi\b|\bfpi\b|investment|infrastructure (financing|funding)|asset monetisation|national monetisation|reit|bond|municipal bond|green bond|sovereign wealth|nif\b|national investment|financing|funding|project finance|concession|toll-operate-transfer|\bepc\b|capital (market|flow)|inflow|fund of funds|angel|venture|startup funding|multilateral/i,
  /science and technology|technolog|artificial intelligence|\bai\b|machine learning|blockchain|5g|drone|3d print|quantum|nano|robot|internet of things|\biot\b|supercomput|genome|crispr|laser|biometric|space|satellite|vaccine|\bmrna\b|semiconductor|digital|\bdata\b|health technology|renewable|everyday life|application|e-?commerce|fintech|cryptocurrenc|bitcoin|metaverse|cloud|big data|autonomous|self-driving|electric vehicle|battery|gene|biotech|stem cell|cloning|telemedicine|ict\b|software|cyber|internet|mobile|telecom|wearable|green hydrogen|fusion|nuclear|hypersonic|missile|defence (technology|production)|lithium/i,
  /achievement|indigeni[sz]ation|indigenous (technology|development|defence)|\bisro\b|\bdrdo\b|chandrayaan|mangalyaan|gaganyaan|nuclear programme|pokhran|light combat|tejas|brahmos|\bagni\b|make in india|atmanirbhar|self[- ]reliance|green revolution|white revolution|satellite launch|cryogenic|gslv|pslv|aditya|astrosat|supercomput|\bparam\b|sarabhai|bhabha|indian scientists?|nobel|c\.?v\.? raman|bose\b|ramanujan|abdul kalam|missile|submarine|aircraft carrier|vikrant|kaveri|arjun tank|\bnavic\b|\bgps\b|digital public|upi|aadhaar|cowin|bt cotton|vaccine|covaxin|startup|space (start|private)|isro|reusable|lvm3|nisar|spadex|technology (development|mission|transfer|absorption)|innovation|r&d|research and development|patent|ip\b/i,
  /\bit\b|information technology|space|computer|robot|nano|bio-?technology|biotech|intellectual property|\bipr\b|patent|copyright|\bgi tag|geographical indication|\btrips\b|cyber|software|startup|genetically|\bgm crops?|stem cell|cloning|\bdna\b|\bgene\b|biosimilar|drone|satellite|data localisation|digital|artificial intelligence|\bai\b|quantum|blockchain|semiconductor|supercomput|3d|iot|5g|ict|internet|e-?commerce|big data|cloud|virtual|augmented|deepfake|genome|crispr|vaccine|mrna|bio-?safety|bio-?piracy|traditional knowledge|neem|turmeric|basmati|trademark|trade secret|tech(nology)? transfer|compulsory licen[cs]|evergreening|doha|launch vehicle|reusable|space debris|asat|anti-?satellite|microorganism|fuel shortage|biofuel|fuel/i,
  /conservation|pollution|degradation|environmental impact|\beia\b|biodiversity|wildlife|climate change|carbon|emission|air quality|water pollution|plastic|waste|forest|coastal regulation|\bcrz\b|ramsar|wetland|mangrove|biosphere|national park|sanctuary|protected area|sustainable|renewable|ozone|greenhouse|paris agreement|\bcop\b|ecolog|green (energy|hydrogen|tribunal|bond)|e-waste|solid waste|noise|desertif|western ghats|himalay|river (pollution|linking)|ganga|namami|environment|species|extinction|endangered|tiger|elephant|rhino|invasive|eco-?sensitive|glacier|coral|soil (erosion|degradation)|groundwater|acid rain|smog|stubble|air pollution|nitrogen|mining|sand mining|deforestation|afforestation|compensatory|cap\b|net zero|adaptation|loss and damage|green growth|circular economy|extended producer|blue economy|ocean acidif|marine|geoengineering|carbon (credit|market|tax)|ecosystem services|rights of nature|polluter pays|precautionary/i,
  /disaster|earthquake|tsunami|flood|cyclone|landslide|drought|\bndma\b|sendai|cloudburst|heat ?wave|relief|rehabilitation|preparedness|mitigation|fire safety|nuclear accident|industrial accident|glacial lake|avalanche|capacity building|early warning|resilien|vulnerab|hazard|ndrf|sdrf|bhopal|chernobyl|fukushima|pandemic|covid|epidemic|urban flood|cloud burst|lightning|forest fire|dam (failure|safety)|stampede|building collapse|response|reconstruction|risk reduction|community-based|indigenous knowledge/i,
  /extremism|naxal|left[- ]wing|maoist|insurgen|radicali[sz]ation|red corridor|tribal.*(development|unrest|alienation)|development.*(extremism|naxal|insurgen)|\blwe\b|north-?east|separatis|terroris|militan|underdevelopment|alienation|deprivation|salwa judum|samadhan|aspirational|fifth schedule|pesa|forest rights|land (alienation|acquisition)|displacement/i,
  /external (state|actor)|non-?state actor|state actor|cross[- ]border|terroris|pakistan|\bisi\b|proxy|foreign (hand|funding|power)|support to|hybrid war|sleeper|hawala|\bfcra\b|china|insurgent group|arms|drug|narco|lashkar|jaish|isis|al-?qaeda|taliban|rohingya|illegal migra|infiltration|radical|extremist group|\bnsa\b|geo-?strategic|great game|encircle|string of pearls|gray zone|grey zone|information warfare|propaganda|cyber (attack|warfare)|stateless|safe haven|state-?sponsored|bangladesh|myanmar|nepal|sri lanka|foreign (interference|intelligence)|mob violence|law and order|mob/i,
  /cyber|social media|social networking|communication network|\bmedia\b|fake news|dark web|cryptocurrenc|hacking|data (breach|protection|theft)|information warfare|money[- ]launder|\bpmla\b|terror financing|\bfatf\b|hawala|surveillance|encryption|internet shutdown|misinformation|disinformation|deepfake|online radicali|cyber (crime|security|terror|attack|space|warfare|law)|\bit act\b|digital (arrest|fraud|security)|ransomware|phishing|malware|critical information infrastructure|cert-in|nciipc|data localisation|whatsapp|facebook|twitter|telegram|vpn|aadhaar|smartphone|net neutrality|e-?commerce fraud|upi fraud|trolling|mob lynching|hate speech|lawful interception/i,
  /border|line of control|\bloc\b|coastal security|maritime security|coastal|smuggling|organi[sz]ed crime|narco|drug trafficking|golden (crescent|triangle)|human trafficking|infiltration|fencing|\bbsf\b|\bitbp\b|assam rifles|island territor|andaman|lakshadweep|siachen|doklam|sea ?lane|piracy|terror|\blac\b|line of actual|border (management|area|infrastructure|disput|guard|trade)|vibrant villages|bop\b|integrated check post|crime-?terror|nexus|arms (smuggling|trafficking)|fake (currency|indian currency)|gold smuggling|poppy|opium|ice\b|methamphetamine|mumbai attack|26\/11|pathankot|uri\b|pulwama|balakot|surgical|ceasefire|cross-?border|riverine|sir creek|ladakh|arunachal|sikkim|eastern ladakh|galwan|depsang/i,
  /security forces?|\bagenc|\bnia\b|\braw\b|\bib\b|\bcbi\b|paramilitary|\bcrpf\b|\bbsf\b|\bcisf\b|\bitbp\b|\bssb\b|coast guard|\bnsg\b|armed forces|police|\barmy\b|\bnavy\b|air force|defence (reform|procurement|budget|production|minister|policy|forces)|theatre command|\bcds\b|intelligence|rapid action|special forces|mandate|\bnsa\b|\bdsci\b|\bndrf\b|\bnatgrid\b|\bnctc\b|\bncrb\b|\bcctns\b|\bpolice (reform|modern)|military|agniveer|agnipath|joint(ness)?|integrated|reorgani[sz]ation|force (structure|multiplier|modern)|national security (strategy|council|doctrine)|nuclear (doctrine|triad|deterrence)|no first use|operation|commando|garuda|marcos|para\b|s-400|air defence|defence system|missile defence|weapon/i
 ],
 "GS Paper IV": [
  /ethic|moral|dimension|private and public|\bvalues?\b|conscience|determinants|virtue|duty|human interface|principle|right and wrong|integrity|honest|dharma|karma|norm|obligation|responsib|good and|justice|fair|truth|non-?violence|ahimsa|forgive|humility|courage|loyalty|selfless|sacrifice|self-?interest|greed|corruption|nepotism|dishonest|moral (courage|compass|dilemma|values|sense|obligation|responsib|standard)/i,
  /attitude|persuasion|prejudice|stereotyp|\bbias|thought and behaviour|social influence|cognitive dissonance|belief|opinion|mindset|perception|behaviour|behavior|influence|political (attitude|neutral)|moral (attitude|and political)|media|propaganda|social media|hate|tolerance|discriminat|conformity|obedience|peer|stigma|communal|casteism|religious/i,
  /aptitude|foundational values|integrity|impartial|non-?partisan|objectiv|dedication|empathy|tolerance|compassion|weaker section|public service|civil service|qualities|characteristic|neutral|honest|leadership|courage|sincerity|commitment|fairness|diligen|perseverance|work ethic|decision[- ]making|spirit of service|service orientation|responsiveness|probity|accountab|competence|merit/i,
  /emotional intelligence|emotional|empathy|self[- ]awareness|self[- ]regulation|social skills?|motivation|anger|stress|emotion|compassion|sympathy|feelings?|resilien|mindfulness|burnout|empathic|emotive|temperament|calm|patience/i,
  /thinker|philosopher|gandhi|kant\b|aristotle|plato|socrates|buddha|mahavira|confucius|kautilya|thiruvalluvar|vivekananda|tagore|ambedkar|\bmill\b|bentham|rawls|utilitarian|sarvodaya|swami|teaching|quote|statement|saying|\bsaid\b|"|“|‘|lessons? from|great leaders|reformers|mother teresa|lincoln|martin luther|mandela|abdul kalam|vinoba|aurobindo|radhakrishnan|sri ?aurobindo|kabir|guru nanak|nanak|raja ram|ram mohan|vidyasagar|jyotiba|phule|periyar|swami dayanand|jiddu|krishnamurti|shankaracharya|gita|upanishad|vedanta|ethics of|hobbes|locke|rousseau|marx|nietzsche|sartre|kierkegaard|machiavelli|adam smith|thoreau|emerson|tolstoy|lao tzu|zen/i,
  /civil service|public service|public administration|administration|government|ethical (concern|dilemma|issue|governance)|accountab|laws, rules|conscience|corporate governance|code of|conflict of interest|whistle|rules and regulations|bureaucra|private (institution|sector|organi)|funding|international relations|ethical|dilemma|official|authority|public (official|servant|interest|trust|money|funds)|political (interference|pressure|neutrality)|transfer|disciplin|sources of ethical|institution|organi[sz]ational|corporate|csr|business ethics|lobby|nepotism|favouritism|misuse|abuse of (power|position)|chain of command|superior|subordinate|obey|orders?|reporting/i,
  /probity|transparency|right to information|\brti\b|codes? of (ethics|conduct)|citizen'?s charter|work culture|quality of service|public funds|corruption|integrity|information sharing|bribery|bribe|nepotism|cronyism|whistle|lokpal|public money|misappropriation|embezzle|graft|kickback|vigilance|audit|conflict of interest|accountab|good governance|philosophical basis|concept of public service|utilization|economy and efficiency|corrupt|black money|disclosure|declaration of assets|asset|gift|hospitality|moral hazard|favour|cash|illegal|irregular/i,
  null
 ]
};

// Questions the keywords do not reach, filed by hand: paper -> "year/qno" -> line numbers
module.exports.overrides = {
 "GS Paper III": {"2014/10":[10], "2018/12":[0], "2022/5":[0]}
};
