// The official UPSC Anthropology syllabus (Examination Notice 05/2026-CSE, Appendix I Section III Part B), item by item.
// Source text: ../syllabus/official-2026/anthropology.txt. These items are the TRUE syllabus; the finer topics in
// anthropology.topics.js are sub-topics filed under them (each topic names its parent in PARENT below).
module.exports.items = [
 // ---- Paper I ----
 {id:"1.1", pp:1, t:"Meaning, scope and development of anthropology"},
 {id:"1.2", pp:1, t:"Relationships with other disciplines: social, behavioural, life, medical and earth sciences and humanities"},
 {id:"1.3", pp:1, t:"Main branches of anthropology: social-cultural, biological, archaeological, linguistic"},
 {id:"1.4", pp:1, t:"Human evolution and emergence of man: biological and cultural factors; theories of organic evolution; synthetic theory and evolutionary concepts"},
 {id:"1.5", pp:1, t:"Primates: characteristics, taxonomy, adaptations, behaviour, fossil and living primates; man and apes; erect posture"},
 {id:"1.6", pp:1, t:"Phylogenetic status of fossil hominids: Australopithecines, Homo erectus, Neanderthal, Rhodesian, Homo sapiens"},
 {id:"1.7", pp:1, t:"The biological basis of life: cell, DNA, protein synthesis, gene, mutation, chromosomes, cell division"},
 {id:"1.8", pp:1, t:"Prehistoric archaeology: principles, dating methods and broad outlines of prehistoric cultures (Palaeolithic to Iron Age)"},
 {id:"2.1", pp:1, t:"The nature of culture: culture and civilisation; ethnocentrism and cultural relativism"},
 {id:"2.2", pp:1, t:"The nature of society: social institutions, groups and social stratification"},
 {id:"2.3", pp:1, t:"Marriage"},
 {id:"2.4", pp:1, t:"Family"},
 {id:"2.5", pp:1, t:"Kinship"},
 {id:"3", pp:1, t:"Economic organisation"},
 {id:"4", pp:1, t:"Political organisation and social control"},
 {id:"5", pp:1, t:"Religion"},
 {id:"6", pp:1, t:"Anthropological theories (a to j)"},
 {id:"7", pp:1, t:"Culture, language and communication"},
 {id:"8", pp:1, t:"Research methods in anthropology"},
 {id:"9.1", pp:1, t:"Human genetics: methods and application"},
 {id:"9.2", pp:1, t:"Mendelian genetics in man"},
 {id:"9.3", pp:1, t:"Genetic polymorphism and selection; Hardy-Weinberg law; inbreeding; genetic load"},
 {id:"9.4", pp:1, t:"Chromosomes and chromosomal aberrations; genetic imprints, screening, counselling, DNA profiling, genome"},
 {id:"9.5", pp:1, t:"Race and racism"},
 {id:"9.6", pp:1, t:"Age, sex and population variation as genetic markers; blood groups; physiological characteristics"},
 {id:"9.7", pp:1, t:"Ecological anthropology: bio-cultural adaptations and responses to environmental stress"},
 {id:"9.8", pp:1, t:"Epidemiological anthropology: health and disease"},
 {id:"10", pp:1, t:"Human growth and development; ageing; physique and somatotypes"},
 {id:"11.1", pp:1, t:"Menarche, menopause and other bio-events; fertility patterns"},
 {id:"11.2", pp:1, t:"Demographic theories: biological, social and cultural"},
 {id:"11.3", pp:1, t:"Factors influencing fecundity, fertility, natality and mortality"},
 {id:"12", pp:1, t:"Applications of anthropology: sports, nutrition, equipment design, forensics, personal identification, applied genetics, DNA technology"},
 // ---- Paper II ----
 {id:"II-1.1", pp:2, t:"Evolution of Indian culture and civilisation: prehistoric to protohistoric; Pre-Harappan, Harappan and post-Harappan; tribal contributions"},
 {id:"II-1.2", pp:2, t:"Palaeo-anthropological evidence from India: Siwaliks and Narmada basin (Ramapithecus, Sivapithecus, Narmada Man)"},
 {id:"II-1.3", pp:2, t:"Ethno-archaeology in India"},
 {id:"II-2", pp:2, t:"Demographic profile of India: ethnic and linguistic elements; population structure and growth"},
 {id:"II-3.1", pp:2, t:"Traditional Indian social system: Varnashram, Purushartha, Karma, Rina and rebirth"},
 {id:"II-3.2", pp:2, t:"Caste system: structure, theories of origin, dominant caste, mobility, future, Jajmani, tribe-caste continuum"},
 {id:"II-3.3", pp:2, t:"Sacred complex and Nature-Man-Spirit complex"},
 {id:"II-3.4", pp:2, t:"Impact of Buddhism, Jainism, Islam and Christianity on Indian society"},
 {id:"II-4", pp:2, t:"Emergence, growth and development of anthropology in India: scholar-administrators and Indian anthropologists"},
 {id:"II-5.1", pp:2, t:"Indian village: village studies, social system, settlement, agrarian relations, globalisation"},
 {id:"II-5.2", pp:2, t:"Linguistic and religious minorities"},
 {id:"II-5.3", pp:2, t:"Socio-cultural change: Sanskritisation, Westernisation, Modernisation; little and great traditions; Panchayati Raj; media"},
 {id:"II-6.1", pp:2, t:"Tribal situation in India: bio-genetic variability, linguistic and socio-economic characteristics, distribution"},
 {id:"II-6.2", pp:2, t:"Problems of tribal communities: land alienation, poverty, indebtedness, literacy, unemployment, health and nutrition"},
 {id:"II-6.3", pp:2, t:"Development projects and displacement; forest policy; urbanisation and industrialisation"},
 {id:"II-7.1", pp:2, t:"Exploitation and deprivation of SC, ST and OBC; constitutional safeguards"},
 {id:"II-7.2", pp:2, t:"Social change and contemporary tribal societies: democratic institutions, development programmes, welfare measures"},
 {id:"II-7.3", pp:2, t:"Ethnicity, ethnic conflict, tribal unrest, regionalism, pseudo-tribalism; social change in colonial and post-Independent India"},
 {id:"II-8.1", pp:2, t:"Impact of Hinduism, Buddhism, Christianity, Islam and other religions on tribal societies"},
 {id:"II-8.2", pp:2, t:"Tribe and nation state: tribal communities in India and other countries"},
 {id:"II-9.1", pp:2, t:"History of tribal administration, policies, plans and programmes; PTGs; role of NGOs"},
 {id:"II-9.2", pp:2, t:"Role of anthropology in tribal and rural development"},
 {id:"II-9.3", pp:2, t:"Contributions of anthropology to understanding regionalism, communalism and ethnic and political movements"}
];
// topic title (first match wins, tested against the title) -> official item id
module.exports.parent = [
 [/^Meaning, scope and relevance/, "1.1"], [/^Relationship with other disciplines/, "1.2"], [/^Branches of anthropology/, "1.3"],
 [/^Biological and cultural factors/, "1.4"], [/^Theories of organic evolution/, "1.4"], [/^Synthetic theory/, "1.4"], [/^Evolutionary rules/, "1.4"],
 [/^Primates: char/, "1.5"], [/^Primate behaviour/, "1.5"], [/^Fossil primates/, "1.5"], [/^Comparative anatomy/, "1.5"],
 [/^Australopithecines/, "1.6"], [/^Homo erectus/, "1.6"], [/^Neanderthal/, "1.6"], [/^Rhodesian/, "1.6"], [/^Homo sapiens/, "1.6"],
 [/^Cell, cell division/, "1.7"], [/^Chromosomes and chromosomal/, "9.4"], [/^DNA, genes/, "9.4"], [/^Mendelian and non/, "9.2"], [/^Methods of studying human genetics/, "9.1"],
 [/^Genetic polymorphism/, "9.3"], [/^Population genetics/, "9.3"], [/^Blood groups/, "9.6"], [/^Physiological characteristics/, "9.6"], [/^Genetic counselling/, "9.4"],
 [/^Principles and field methods/, "1.8"], [/^Dating methods/, "1.8"], [/^Cultural evolution and V\. Gordon/, "6"], [/^Palaeolithic cultures of the world/, "1.8"], [/^Mesolithic cultures of the world/, "1.8"], [/^Neolithic and the origin/, "1.8"], [/^Chalcolithic, Bronze/, "1.8"],
 [/^Concept and characteristics of culture/, "2.1"], [/^Cultural relativism/, "2.1"], [/^Society, social institutions/, "2.2"], [/^Social stratification/, "2.2"],
 [/^Marriage/, "2.3"], [/^Family/, "2.4"], [/^Descent, descent/, "2.5"], [/^Kinship terminology/, "2.5"], [/^Alliance theory/, "2.5"],
 [/^Economic anthropology/, "3"], [/^Production, distribution/, "3"], [/^Modes of subsistence/, "3"], [/^Globalisation, indigenous/, "3"],
 [/^Political organisation/, "4"], [/^Social control/, "4"],
 [/^Anthropological approaches to religion/, "5"], [/^Religion, magic/, "5"], [/^Totemism/, "5"], [/^Traditional forms of religion/, "5"],
 [/^Classical evolutionism/, "6"], [/^Historical particularism/, "6"], [/^Functionalism/, "6"], [/^Structuralism/, "6"], [/^Culture and personality/, "6"], [/^Neo-evolutionism/, "6"], [/^Cultural materialism/, "6"], [/^Symbolic/, "6"], [/^Cognitive/, "6"], [/^Post-modernism/, "6"],
 [/^Language and communication/, "7"],
 [/^Fieldwork tradition/, "8"], [/^Tools of data/, "8"], [/^Sampling/, "8"], [/^Participatory methods/, "8"],
 [/^Anthropometry and somatotypes/, "10"], [/^Methods of studying growth/, "10"], [/^Growth: stages/, "10"], [/^Ageing/, "10"],
 [/^Menarche/, "11.1"], [/^Demography/, "11.2"], [/^Fertility, fecundity/, "11.3"],
 [/^Ergonomics/, "12"], [/^Nutritional anthropology/, "12"], [/^Sports/, "12"], [/^Forensic/, "12"], [/^DNA technology in disease/, "12"],
 [/^Race, racism/, "9.5"], [/^Human adaptation/, "9.7"], [/^Epidemiological/, "9.8"],
 [/^Palaeolithic cultures of India/, "II-1.1"], [/^Mesolithic cultures of India/, "II-1.1"], [/^Neolithic cultures of India/, "II-1.1"], [/^Chalcolithic, Iron/, "II-1.1"], [/^Harappan/, "II-1.1"], [/^Prehistoric rock art/, "II-1.1"], [/^Tribal contribution/, "II-1.1"],
 [/^Palaeo-anthropology of India/, "II-1.2"], [/^Ethno-archaeology/, "II-1.3"],
 [/^Ethnic and racial classification/, "II-2"], [/^Linguistic elements/, "II-2"], [/^Population growth/, "II-2"],
 [/^Varnashrama/, "II-3.1"], [/^Caste system/, "II-3.2"], [/^Caste mobility$/, "II-3.2"], [/^Dominant caste/, "II-3.2"], [/^Jajmani/, "II-3.2"], [/^Tribe-caste/, "II-3.2"],
 [/^Sacred complex/, "II-3.3"], [/^Buddhism, Jainism/, "II-3.4"], [/^Islam, Sufism/, "II-3.4"],
 [/^Colonial ethnography/, "II-4"], [/^Contributions of Indian anthropologists/, "II-4"],
 [/^Indian village/, "II-5.1"], [/^Religious and linguistic minorities/, "II-5.2"],
 [/^Sanskritisation, Westernisation/, "II-5.3"], [/^Great and Little/, "II-5.3"], [/^Media/, "II-5.3"],
 [/^Concept of tribe/, "II-6.1"], [/^Distribution, classification/, "II-6.1"], [/^Tribal social institutions/, "II-6.1"], [/^Nomadic, pastoral/, "II-6.1"], [/^Particularly Vulnerable/, "II-9.1"],
 [/^Land alienation/, "II-6.2"], [/^Poverty, indebtedness/, "II-6.2"], [/^Tribal education/, "II-6.2"], [/^Tribal health/, "II-6.2"],
 [/^Forest policy/, "II-6.3"], [/^Displacement/, "II-6.3"], [/^Impact of globalisation, industrialisation/, "II-6.3"],
 [/^Scheduled Castes, OBCs/, "II-7.1"], [/^Constitutional safeguards/, "II-7.1"],
 [/^PESA/, "II-7.2"], [/^Tribal women/, "II-7.2"],
 [/^Ethnicity, regionalism/, "II-7.3"], [/^Tribal unrest/, "II-7.3"], [/^Pseudo-tribalism/, "II-7.3"],
 [/^Impact of Hinduism/, "II-8.1"], [/^Tribe and nation state/, "II-8.2"],
 [/^Tribal policy/, "II-9.1"], [/^NGOs and missionaries/, "II-9.1"], [/^Role of anthropology in tribal/, "II-9.2"], [/^Anthropological understanding of regionalism/, "II-9.3"]
];
