// Commerce and Accountancy optional: syllabus sub-topics in syllabus order, with the words that tie a past question to each.
//   s    : the official item (I-A1a ... II-B2g) the sub-topic is filed under (see items.js)
//   re   : pattern tested against the question text (case-insensitive); written as a regex literal, stored as its source
//   ex   : a question that also matches this is NOT filed under the topic
//   refs : questions filed here by hand (year|paper|qno) because their text does not carry the words (the data is in the figure)
//   fb   : true = fallback topic, used only for a question that no other topic claims
//   p    : 1 or 2 limits the topic to that paper (omit = both)
// A question can belong to several topics (UPSC often joins two ideas in one question).
// Re-run with:  node upsc-pyq-bank/tools/optional/commerce-and-accountancy/build-commerce.js
const S = function(r){ return r.source; };
module.exports = [
 // ================= PAPER I =================
 {s:"I-A1a", p:1, t:"Accounting standards: depreciation, inventories, revenue, fixed assets, contingencies, foreign exchange, government grants, EPS", re:S(/accounting standard|\bAS[- ]?\d|depreciation|inventor(y|ies) valuation|valuation of inventor|revenue recognition|construction contract|research and development|foreign exchange|government grant|earnings per share|\bEPS\b.{0,30}(account|standard)|contingen(t|cies)|fixed assets|impact of behavio|financial information system|recognition of revenue|accounting is an information|accounting (theory|concept|convention|principle)|GAAP/), ex:S(/EBIT|dividend (policy|decision)|capital structure/)},
 {s:"I-A1a", p:1, t:"Cash flow statement", re:S(/cash flow statement|statement of cash flow|cash flow from (operating|investing|financing)|indirect method|direct method|cash from operating/)},
 {s:"I-A1b", p:1, t:"Share capital: issue, forfeiture, re-issue, bonus and right shares", re:S(/share capital|issue of shares|forfeit|re-?issue|bonus (share|issue)|right (share|issue)|rights issue|preference share|redemption of (preference|debenture)|underwrit|calls? in arrear|oversubscri|allot/), ex:S(/amalgamat|absorption/)},
 {s:"I-A1c", p:1, t:"Employee stock options and buy-back of securities", re:S(/stock option|ESOP|ESOS|buy[- ]?back|sweat equity/)},
 {s:"I-A1d", p:1, t:"Company final accounts: balance sheet, profit and loss account and managerial remuneration", re:S(/final accounts|balance sheet of|prepare.{0,40}balance sheet|profit and loss (account|statement)|schedule iii|managerial remuneration|debenture|goodwill|valuation of (shares|goodwill)|holding compan|subsidiary|consolidat|liquidat|winding up|statement of affairs|insurance claim|royalt|hire[- ]purchase|branch account|departmental|partnership|dissolution|admission of a partner|retirement of a partner/), ex:S(/amalgamat|absorption|reconstruction|ratios?\b|cash flow statement/)},
 {s:"I-A1e", p:1, t:"Amalgamation, absorption, internal and external reconstruction", re:S(/amalgamat|absorption|reconstruction|purchase consideration|take[- ]?over of|merger of/), ex:S(/types of mergers|financial objectives of mergers|corporate restructuring/)},
 {s:"I-A2a", p:1, t:"Cost accounting: nature, concepts, cost sheet, cost control and cost reduction, installation", re:S(/cost accounting|cost sheet|cost unit|cost concept|cost centre|installation of|costs used in|costing system|cost control|cost reduction|overheads?|absorption of overhead|reconciliation of cost|cost audit|inventory control|economic order quantity|\bEOQ\b|stores? (control|ledger)|labour cost|idle time|incentive wage|opportunity cost|sunk cost|contract (account|costing)|operating costing|unit costing|batch costing|service costing|transport cost/), ex:S(/job cost|process cost|activity[- ]based/)},
 {s:"I-A2b", p:1, t:"Job, process and activity based costing", re:S(/job cost|process cost|activity[- ]based|\bABC\b|cost driver|process account|equivalent units?|abnormal (loss|gain)|normal loss|joint product|by-?product|godown|process a\/c/)},
 {refs:["2023|1|2(b)"], s:"I-A2c", p:1, t:"Cost-volume-profit analysis, break-even and profit planning", re:S(/profit[- ]volume|P\/V|\bPV ratio|break[- ]?even|margin of safety|cost[- ]volume|volume[- ]cost|marginal cost|contribution|profit planning|key factor|limiting factor/), ex:S(/make or buy|shut[- ]?down|pricing decision|differential cost|incremental/)},
 {refs:["2022|1|2(b)"], s:"I-A2d", p:1, t:"Differential costing and incremental analysis: pricing, make or buy, shut-down and product decisions", re:S(/differential cost|incremental (analysis|cost|revenue)|make or buy|make-or-buy|shut[- ]?down|pricing decision|product mix|special order|accept(ing)? (an? )?(export|special) order|transfer pric|selling price decision|sell or process further|dropping a product/)},
 {s:"I-A2e", p:1, t:"Budgeting, standard costing and variance analysis", re:S(/budget|standard cost|variance|standard (mix|price|rate|hours)|flexible budget|zero[- ]base|performance budget|master budget|cash budget|material (price|usage|yield|mix) |labour (rate|efficiency)/)},
 {s:"I-A2f", p:1, t:"Responsibility accounting and divisional performance measurement", re:S(/responsibility accounting|responsibility cent|divisional (performance|profit|manager)|return on investment|\bROI\b|residual income|investment cent|profit cent|cost cent.{0,30}responsib|balanced scorecard|economic value added|\bEVA\b/)},
 {s:"I-A3a", p:1, t:"Income tax: heads of income, residential status and computation for individuals", re:S(/income tax|assessment year|previous year|residential status|salary|salaries|perquisite|house property|annual (letting )?value|capital gain|business or profession|profits and gains|income from other sources|total income|computation of (total )?income|taxable income|agricultural income|exempt(ed)? income|incomes which do not form|clubbing|income of other persons|\bPAN\b|advance tax|TDS|tax deducted at source|gratuity|HRA|house rent allowance|pension|depreciation under (the )?income|interest on securities|gifts?\b.{0,20}(tax|received)|capital asset|long[- ]term capital|short[- ]term capital|STT\b|donation|liable in respect of his own|pays tax on his own incomes|income from business/)},
 {s:"I-A3b", p:1, t:"Set-off and carry forward of losses", re:S(/set[- ]off|carry forward|carried forward.{0,30}loss|brought forward loss|unabsorbed depreciation|loss under the head/)},
 {s:"I-A3c", p:1, t:"Deductions from gross total income (Chapter VI-A)", re:S(/deduction(s)? (under|from|u\/s)|section 80|80[A-Z]{1,3}\b|chapter VI-?A|gross total income/)},
 {s:"I-A3d", p:1, t:"VAT, service tax and GST", re:S(/\bVAT\b|value added tax|service tax|\bGST\b|goods and services tax|input tax credit|cenvat|central excise|sales tax|customs duty/)},
 {s:"I-A4a", p:1, t:"Company audit: auditor, divisible profits, dividends, special investigation and tax audit", re:S(/\baudit(or|ors|ing)?\b|investigat|divisible profit|dividend.{0,40}(audit|declar|payable out)|tax audit|vouching|verification|internal (check|control)|internal audit|management audit|audit report|audit programme|auditor'?s (duty|report|right|liabilit|independence)|true and fair|qualified report|CARO|statutory audit|fraud/), ex:S(/bank(ing)? (audit|compan)|insurance|non-profit|charitable|trust/)},
 {s:"I-A4b", p:1, t:"Audit of banks, insurance companies, non-profit organisations and charitable trusts", re:S(/audit(ing)? of (a )?(bank|insurance|charit|trust|non-?profit|club|educational|hospital|society|co-?operative)|bank(ing)? audit|insurance (company|audit)|non-?profit|charitable (trust|society|organi[sz]ation|institution)|trust(s)? (account|audit)|auditing the accounts of/)},
 {s:"I-B1a", p:1, t:"Finance function, objectives of financial management and risk-return relationship", re:S(/finance function|objectives? of (financial management|the firm)|wealth maximi[sz]ation|profit maximi[sz]ation|scope of financial management|nature of financial management|risk and return|risk-return|agency (problem|cost|theory)|role of (a )?finance manager|time value of money|financial manager|financial decision|wealth of shareholders/)},
 {s:"I-B1b", p:1, t:"Ratio analysis, funds flow statement and cash flow analysis", re:S(/ratio|funds? flow|sources and uses of funds|statement of changes in financial position|financial (statement )?analysis|common[- ]size|trend analysis|du pont|working capital.{0,30}statement of changes/)},
 {s:"I-B1c", p:1, t:"Capital budgeting: appraisal methods, NPV, IRR, payback, risk and uncertainty analysis", re:S(/capital budgeting|capital expenditure|net present value|\bNPV\b|internal rate of return|\bIRR\b|pay[- ]?back|profitability index|discounted cash|accounting rate of return|\bARR\b|investment (decision|proposal|appraisal)|risk-adjusted|certainty equivalent|sensitivity analysis|simulation|decision[- ]tree|capital rationing|project (appraisal|evaluation|selection)|equipment/), ex:S(/venture capital/)},
 {s:"I-B1d", p:1, t:"Cost of capital: specific costs, WACC and CAPM", re:S(/cost of (capital|equity|debt|preference|retained)|\bWACC\b|weighted average cost|CAPM|capital asset pricing|beta\b|security market line|required (rate of )?return|cost of capital/)},
 {s:"I-B1e", p:1, t:"Capital structure theories and leverages: NI, NOI, MM and traditional approach, EBIT-EPS analysis", re:S(/capital structure|net income approach|net operating income|\bNOI\b|modigliani|miller|traditional (approach|theory|view)|leverage|gearing|EBIT[- ]EPS|financial plan|optimal capital|indifference point|degree of (operating|financial|combined)|trading on equity|arbitrage|\bMM\b/), ex:S(/dividend/)},
 {s:"I-B1f", p:1, t:"Dividend decisions: Walter, Gordon, MM and Lintner models and dividend policy", re:S(/dividend (policy|decision|model|payout|theory|irrelevance|relevance)|walter|gordon|lintner|bird in (the )?hand|payout ratio|retention ratio|stock split|bonus shares?.{0,30}dividend|dividend/), ex:S(/audit/)},
 {s:"I-B1g", p:1, t:"Working capital: planning, determinants, cash, inventory and receivables management", re:S(/working capital|cash management|cash cycle|operating cycle|receivable|credit (policy|period|terms)|debtors? (management|collection)|factoring|inventory (management|control)|baumol|miller-?orr|lock[- ]?box|float|trade credit|collection period|cash discount|bad debts? (policy|loss)|credit rating of customers/), ex:S(/credit rating agenc/)},
 {s:"I-B1h", p:1, t:"Corporate restructuring: mergers, acquisitions and takeovers (financial aspects)", re:S(/merger|acquisition|takeover|take-over|corporate restructuring|demerger|leveraged buy|swap ratio|exchange ratio|synergy|divestiture|spin[- ]?off|buy[- ]?out/), ex:S(/amalgamation in the nature|purchase consideration/)},
 {s:"I-B2a", p:1, t:"Indian financial system: overview, structure, institutions and reforms", re:S(/financial system|financial institution|financial sector|development financ|\bIDBI\b|\bSIDBI\b|\bNABARD\b|\bIFCI\b|\bUTI\b|\bLIC\b|\bEXIM\b|term[- ]lending|financial intermediar|non-banking|\bNBFC|financial inclusion|financial reform|\bFEMA\b|foreign direct|FDI|FII|foreign institutional/)},
 {s:"I-B2b", p:1, t:"Money market, commercial banks, banking reforms and the monetary policy and regulatory role of RBI", re:S(/money market|call money|treasury bill|commercial paper|certificate of deposit|repo|reverse repo|commercial bank|banking (sector|reform)|monetary (and credit )?policy|credit (control|policy)|reserve bank|\bRBI\b|\bCRR\b|\bSLR\b|bank rate|NPA|non-performing|basel|capital adequacy|bank(s)? (nationali|merger|licen)|payment bank|small finance bank|inflation targeting|liquidity adjustment/)},
 {s:"I-B2c", p:1, t:"Capital market: primary and secondary markets, instruments, innovative debt instruments and SEBI", re:S(/capital market|primary market|secondary market|stock exchange|\bIPO\b|initial public offer|book[- ]?building|new issue|public issue|green[- ]?shoe|depositor|dematerial|\bSEBI\b|securities and exchange board|innovative (debt )?instrument|zero[- ]coupon|deep[- ]discount|floating rate|convertible (debenture|bond)|junk bond|securiti[sz]ation|derivative|futures|options|stock market|insider trading|market (maker|capitalisation)|sensex|nifty|share market|rights issue|bond market|debt market|global depository|ADR\b|GDR\b|ECB\b|private placement/)},
 {s:"I-B2d", p:1, t:"Financial services: mutual funds, venture capital, credit rating, insurance and IRDA", re:S(/mutual fund|venture capital|credit rating|crisil|rating methodology|rating agenc|insurance|IRDA|IRDAI|leasing|hire purchase finance|merchant bank|factoring|forfaiting|financial services|depository services|portfolio management|underwriting|credit card|housing finance|microfinance|private equity|angel invest|start-?up/), ex:S(/audit/)},
 // ================= PAPER II =================
 {s:"II-A1a", p:2, t:"Organisation: concept, environment, goals, strategy and management by objectives", re:S(/organi[sz]ations? (are|have been) (defined|collectivities)|how have organi[sz]ations been defined|nature (and|of).{0,15}organi[sz]ation|concept of organi[sz]ation|external environment|environment(al)? (of|a major|is a)|political and legal environment|technological environment|organi[sz]ational goal|primary and secondary goal|single and multiple goal|management by objectives?|\bMBO\b|strategy-structure|strategy and structure|learning organi[sz]ation|corporate governance|social responsibility|business environment|stakeholder|organi[sz]ational effectiveness|organi[sz]ational environment|internal and external changes|importance of goals|organisation without goals|profit maximization as a goal/), ex:S(/matrix/)},
 {s:"II-A1b", p:2, t:"Evolution of organisation theory: classical, neo-classical, systems and contingency approaches", re:S(/classical|neo-?classical|scientific management|taylor|fayol|weber|bureaucra|human relations|hawthorne|systems? (approach|theory)|contingency (approach|theory|view)|social system|ritualism|red-?tapism|principles of management|administrative (theory|principle)|management by exception|modern (organi[sz]ation )?theory|critics? of organi[sz]ational theory/), ex:S(/leader|fiedler/)},
 {s:"II-A1c", p:2, t:"Modern concepts: organisational design, structure, virtual organisation and re-engineering", re:S(/organi[sz]ational design|organi[sz]ation(al)? structure|virtual organi[sz]ation|re-?engineering|boundary ?less|learning organi[sz]ation|empowered organi[sz]ation|structural dimension|network organi[sz]ation|flat organi[sz]ation|downsizing|outsourcing.{0,30}organi[sz]ation|restructuring of organi[sz]ation|strategic alignment|designing/), ex:S(/matrix|line and staff|centrali[sz]ation|decentrali[sz]ation/)},
 {s:"II-A1d", p:2, t:"Organisational design: differentiation, centralisation, delegation, span of management and formal-informal organisations", re:S(/centrali[sz]ation|decentrali[sz]ation|delegat|span of (management|control)|unity of command|scalar|chain of command|formali[sz]ation|standardi[sz]ation|mutual adjustment|mechanistic|organic (structure|system)|informal organi[sz]ation|formal organi[sz]ation|differentiation and integration|coordination|authority and responsibility|accountability|authority\b/), ex:S(/matrix|line and staff/)},
 {s:"II-A1e", p:2, t:"Organisation structures: line and staff, functional, matrix and project; power and politics; impact of IT", re:S(/line and staff|staff (function|authority)|functional (structure|organi[sz]ation)|matrix|project (structure|organi[sz]ation)|divisional structure|types of organi[sz]ation(al)? structure|source(s)? of power|basis of power|power (structure|tactic|and politic)|tactics.{0,30}power|organi[sz]ational (politics|power)|politics in organi[sz]ation|information technology|impression management|power is used|political power/)},
 {s:"II-A1f", p:2, t:"Organisational culture: nature, creation, change and management", re:S(/organi[sz]ational culture|corporate culture|culture (change|of an organi)|managing (organi[sz]ational )?culture|subculture|norms\b|octapac|work culture|values and (beliefs|norms)|rules are different from norms/)},
 {s:"II-A2a", p:2, t:"Personality, perception, learning and attitudes of the individual in the organisation", re:S(/personality|perception|perceptual|attitude|learning\b|freud|trait|johari|self[- ]concept|emotional intelligence|stereotyp|halo|projection|ego state|attribution|values? system|job satisfaction|stress|coping|repertory grid|impression|supervisor may treat/), ex:S(/transactional analysis/)},
 {s:"II-A2b", p:2, t:"Motivation: Maslow, Herzberg, McGregor, expectancy, equity and Porter-Lawler theories; job design and rewards", re:S(/motivat|maslow|herzberg|mcgregor|theory x|vroom|expectancy|porter[- ]lawler|equity theory|adams|alderfer|mcclelland|achievement need|need hierarchy|two-factor|job (design|enrichment|enlargement|rotation)|flexi-?time|reward system|morale/)},
 {s:"II-A2b", p:2, t:"Leadership: theories, styles and managerial grid", re:S(/leader|managerial grid|tridimensional|path-goal|fiedler/)},
 {s:"II-A2b", p:2, t:"Quality of work life and quality circles", re:S(/quality of work life|quality of working life|\bQWL\b|quality circle/)},
 {s:"II-A2b", p:2, t:"Conflict, transactional analysis, organisational change, effectiveness and group behaviour", re:S(/conflict|transactional analysis|change[sd]?\b|resistance to|organi[sz]ational (development|effectiveness)|\bOD\b|team|group (dynamics|behaviou?r|cohesive)|organi[sz]ational behaviou?r|production cost/)},
 {s:"II-B1a", p:2, t:"HRM: nature and scope, human resource planning, job analysis, description and specification", re:S(/human resource|\bHRM\b|\bHRD\b|\bHR\b|manpower|personnel|job (analysis|description|specification)|job-description|job-psychographic|talent|outsourcing|career|succession/), ex:S(/trade union|industrial dispute|collective bargaining/)},
 {s:"II-B1a", p:2, t:"Recruitment, selection, orientation and placement", re:S(/recruit|selection|tests? are useful|induction|orientation|placement/)},
 {s:"II-B1a", p:2, t:"Training and development, management development", re:S(/training|development program|management development|executive development/)},
 {s:"II-B1a", p:2, t:"Performance appraisal and 360 degree feedback", re:S(/appraisal|performance management|360/)},
 {s:"II-B1a", p:2, t:"Salary and wage administration, job evaluation, incentives and employee welfare", re:S(/wage|salary|compensation|incentive|welfare|job evaluation|job-evaluation|profit[- ]sharing|employee (engagement|benefit)/)},
 {s:"II-B1a", p:2, t:"Promotions, transfers and separations", re:S(/promotion|transfer|separation|exit policy|retrenchment|lay-?off|attrition|turnover|retention|golden handshake|merit/)},
 {s:"II-B2a", p:2, t:"Industrial relations: nature, scope, importance and trade unions", re:S(/industrial relations?|\bIR\b|labour relations|trade union|labour union|union (demand|recogni|leader|rivalry)|recognition of (trade )?union|multiplicity of unions|inter-?union|political (affiliation|involvement) of union|standing orders|labour law|labour legislation|industrial harmony|unfair labour|industrial peace|dunlop|jurisprudence|workers and management|employer-?employee/)},
 {s:"II-B2b", p:2, t:"Liberalisation and the trade union movement", re:S(/liberali[sz]ation|globali[sz]ation.{0,40}(union|labour)|new economic policy|structural adjustment|impact of (reforms|economic)/)},
 {s:"II-B2c", p:2, t:"Industrial disputes: strikes, lockouts, causes, prevention and settlement", re:S(/industrial dispute|strike|lock-?out|grievance|conciliation|arbitration|code of discipline|prevention and settlement|settlement of (dispute|industrial)|industrial truce|works committee|bipartite|tripartite|disciplinary|domestic enquiry|gherao|boycott/)},
 {s:"II-B2d", p:2, t:"Workers' participation in management and industrial democracy", re:S(/participation|industrial democracy|worker'?s? director|joint (management|consultation)|co-?determination|quality of working life.{0,20}participation/)},
 {s:"II-B2e", p:2, t:"Adjudication and collective bargaining", re:S(/adjudicat|collective bargain|tribunal|labour court|bargaining|wage board|settlement/)},
 {s:"II-B2f", p:2, t:"Industrial relations in public enterprises; absenteeism and labour turnover", re:S(/public (sector|enterprise)|PSU|absentee|labour turnover|employee turnover|attrition/), ex:S(/it companies/)},
 {s:"II-B2g", p:2, t:"ILO: functions, organs and conventions", re:S(/\bILO\b|international labour|labour conventions?/)},
 // fallback: a question that no other topic claimed
 {fb:true, s:"II-A1a", p:2, t:"Other organisation, behaviour and human resource questions", re:S(/./)},
];
